from .core import B, E, F, domain, register

# ---------------------------------------------------------------- FINTECH
d = domain("fintech", "digital banking app", "dijital bankacılık uygulaması", "FIN",
           ["Cards", "Payments", "Onboarding", "Accounts", "Notifications",
            "Fraud", "Statements", "Mobile App"])
register(d, features=[
 F("card-freeze", "settings", "Cards", ["cards", "self-service"],
   ("retail banking customer", "bireysel bankacılık müşterisi"),
   ("freeze and unfreeze my debit card instantly from the app",
    "banka kartımı uygulamadan anında dondurup açmak"),
   ("I can stop fraudulent spending without calling the call centre",
    "çağrı merkezini aramadan sahte harcamayı durdurabileyim"),
   dict(obj_en="card freeze toggle", obj_tr="kart dondurma anahtarı",
        surface_en="Cards screen", surface_tr="Kartlarım ekranı"), points=5),
 F("spending-limits", "form", "Cards", ["cards", "limits"],
   ("account holder", "hesap sahibi"),
   ("set a monthly spending limit per card",
    "her kart için aylık harcama limiti belirlemek"),
   ("I can keep my budget under control without checking the app daily",
    "her gün uygulamaya bakmadan bütçemi kontrol altında tutabileyim"),
   dict(obj_en="spending limit", obj_tr="harcama limiti",
        surface_en="Card settings", surface_tr="Kart ayarları"), points=5),
 F("iban-copy", "form", "Accounts", ["ux", "accounts"],
   ("current account user", "vadesiz hesap kullanıcısı"),
   ("copy my IBAN with one tap and share it as formatted text",
    "IBAN'imi tek dokunuşla kopyalayıp biçimli metin olarak paylaşmak"),
   ("I can send my account details to someone without typos",
    "hesap bilgilerimi hatasız şekilde biri ile paylaşabileyim"),
   dict(obj_en="IBAN share sheet", obj_tr="IBAN paylaşım ekranı",
        surface_en="Account detail", surface_tr="Hesap detayı"), points=2),
 F("scheduled-transfer", "payment", "Payments", ["payments", "scheduling"],
   ("salaried customer", "maaşlı müşteri"),
   ("schedule a recurring transfer on a fixed day each month",
    "her ay sabit bir günde tekrarlanan havale talimatı vermek"),
   ("my rent is paid on time even when I forget",
    "unutsam bile kiram zamanında ödenmiş olsun"),
   dict(obj_en="recurring transfer", obj_tr="düzenli ödeme talimatı",
        surface_en="Transfers", surface_tr="Para transferi"), points=8),
 F("kyc-liveness", "upload", "Onboarding", ["kyc", "compliance"],
   ("new applicant", "yeni başvuru sahibi"),
   ("complete identity verification with a selfie liveness check",
    "selfie canlılık kontrolüyle kimlik doğrulamasını tamamlamak"),
   ("I can open an account without visiting a branch",
    "şubeye gitmeden hesap açabileyim"),
   dict(obj_en="liveness check", obj_tr="canlılık kontrolü",
        surface_en="Onboarding step 3", surface_tr="Başvuru 3. adım"), points=13),
 F("txn-search", "search", "Statements", ["search", "statements"],
   ("customer reviewing expenses", "harcamalarını inceleyen müşteri"),
   ("search my transactions by merchant name, amount range and date",
    "işlemlerimi işyeri adı, tutar aralığı ve tarihe göre aramak"),
   ("I can find a specific payment without scrolling months of history",
    "aylarca geçmişi kaydırmadan belirli bir ödemeyi bulabileyim"),
   dict(obj_en="transaction search", obj_tr="işlem arama",
        surface_en="Statements screen", surface_tr="Hesap hareketleri"), points=8),
 F("fraud-alert", "notify", "Fraud", ["fraud", "push"],
   ("card holder", "kart sahibi"),
   ("receive a push notification within seconds of a suspicious transaction",
    "şüpheli bir işlemden saniyeler içinde push bildirimi almak"),
   ("I can block the card before more money is taken",
    "daha fazla para çekilmeden kartı bloke edebileyim"),
   dict(obj_en="fraud alert", obj_tr="dolandırıcılık uyarısı",
        surface_en="Notification centre", surface_tr="Bildirim merkezi"), points=8),
 F("stmt-pdf", "export", "Statements", ["export", "statements"],
   ("customer applying for a visa", "vize başvurusu yapan müşteri"),
   ("download an official stamped PDF statement for a date range",
    "seçtiğim tarih aralığı için resmi kaşeli PDF hesap özeti indirmek"),
   ("I can submit proof of income without going to a branch",
    "şubeye gitmeden gelir belgemi sunabileyim"),
   dict(obj_en="PDF statement", obj_tr="PDF hesap özeti",
        surface_en="Statements screen", surface_tr="Hesap özetleri"), points=5),
 F("biometric-login", "auth", "Mobile App", ["auth", "security"],
   ("returning user", "tekrar giriş yapan kullanıcı"),
   ("log in with Face ID instead of typing my password",
    "şifre yazmak yerine Face ID ile giriş yapmak"),
   ("I can check my balance in seconds",
    "bakiyeme saniyeler içinde bakabileyim"),
   dict(obj_en="biometric login", obj_tr="biyometrik giriş",
        surface_en="Login screen", surface_tr="Giriş ekranı"), points=5),
 F("dispute-flow", "form", "Payments", ["disputes", "support"],
   ("customer who spotted a wrong charge", "hatalı harcama fark eden müşteri"),
   ("raise a dispute for a transaction directly from its detail page",
    "bir işlem için itirazı doğrudan işlem detayından başlatmak"),
   ("I get my money back without a 20 minute phone call",
    "20 dakikalık telefon görüşmesi yapmadan paramın iadesini alabileyim"),
   dict(obj_en="dispute request", obj_tr="itiraz talebi",
        surface_en="Transaction detail", surface_tr="İşlem detayı"), points=8),
], bugs=[
 B("otp-expiry", "Onboarding", ["otp", "auth"],
   ("SMS OTP is rejected as expired after ~30 seconds",
    "SMS OTP yaklaşık 30 saniye sonra süresi dolmuş olarak reddediliyor"),
   ("entering the OTP code on the signup screen",
    "kayıt ekranında OTP kodunu girerken"),
   ("the code stays valid for the documented 180 seconds",
    "kod dokümante edilen 180 saniye boyunca geçerli kalmalı"),
   ("'Code expired, request a new one' is shown after 30s",
    "30 saniye sonra 'Kodun süresi doldu, yeni kod isteyin' hatası gösteriliyor"),
   "AuthService: OtpExpiredException token_ttl=30 expected=180", "Major", "backend"),
 B("balance-stale", "Accounts", ["cache", "accounts"],
   ("account balance shows the previous day's value after an incoming transfer",
    "gelen havale sonrası hesap bakiyesi bir önceki günün değerini gösteriyor"),
   ("pulling to refresh the accounts list right after a transfer lands",
    "havale düştükten hemen sonra hesap listesini aşağı çekip yenilerken"),
   ("the balance reflects the transfer immediately",
    "bakiye havaleyi anında yansıtmalı"),
   ("the old balance persists until the app is force-closed",
    "uygulama zorla kapatılana kadar eski bakiye kalıyor"),
   "cache-key account:{id}:balance ttl=900s, no invalidation on ledger event", "Major", "backend"),
 B("card-freeze-race", "Cards", ["cards", "race-condition"],
   ("a frozen card still authorises contactless payments for a few minutes",
    "dondurulmuş kart birkaç dakika daha temassız ödemeleri onaylıyor"),
   ("freezing the card and immediately tapping at a POS terminal",
    "kartı dondurup hemen POS cihazına temas ettirdiğinde"),
   ("the very next authorisation is declined",
    "hemen sonraki yetkilendirme reddedilmeli"),
   ("authorisations succeed for up to 4 minutes after the freeze",
    "dondurma işleminden sonra 4 dakikaya kadar yetkilendirmeler başarılı oluyor"),
   "card_status replicated to auth-switch via nightly batch, not event stream", "Critical", "backend"),
 B("amount-rounding", "Payments", ["money", "rounding"],
   ("split payments lose one kurus on odd amounts",
    "tek tutarlı bölünmüş ödemelerde bir kuruş kayboluyor"),
   ("splitting a 10,01 TL bill between three people",
    "10,01 TL'lik bir hesabı üç kişiye bölerken"),
   ("the three parts sum exactly to the original amount",
    "üç parçanın toplamı orijinal tutara birebir eşit olmalı"),
   ("the parts sum to 10,00 TL and the remainder is dropped",
    "parçaların toplamı 10,00 TL çıkıyor ve kalan kuruş düşüyor"),
   "float arithmetic in SplitCalculator.divide(); should use Decimal/minor units", "Major", "backend"),
 B("statement-tz", "Statements", ["timezone", "reporting"],
   ("transactions made after 21:00 appear on the next day's statement",
    "21:00'dan sonra yapılan işlemler bir sonraki günün ekstresinde görünüyor"),
   ("viewing the daily statement for a day with late-evening transactions",
    "akşam geç saatte işlem yapılan bir günün günlük ekstresini görüntülerken"),
   ("transactions are grouped by the customer's local day",
    "işlemler müşterinin yerel gününe göre gruplanmalı"),
   ("grouping uses UTC, shifting Istanbul transactions by 3 hours",
    "gruplama UTC kullanıyor, İstanbul işlemlerini 3 saat kaydırıyor"),
   "statement_service groups on created_at UTC, ignores user tz offset", "Minor", "data"),
 B("push-duplicate", "Notifications", ["push", "duplicate"],
   ("users receive the same fraud alert three to five times",
    "kullanıcılar aynı dolandırıcılık uyarısını üç ile beş kez alıyor"),
   ("a suspicious transaction triggers an alert while the app is backgrounded",
    "uygulama arka plandayken şüpheli işlem uyarısı tetiklendiğinde"),
   ("exactly one notification is delivered per alert",
    "uyarı başına tam olarak bir bildirim iletilmeli"),
   ("3-5 identical notifications arrive within 10 seconds",
    "10 saniye içinde 3-5 aynı bildirim geliyor"),
   "Kafka consumer without idempotency key; redelivery on rebalance", "Minor", "backend"),
 B("kyc-upload-ios", "Onboarding", ["mobile", "ios", "upload"],
   ("ID photo upload fails silently on iOS when HEIC format is used",
    "iOS'ta HEIC formatında kimlik fotoğrafı yüklemesi sessizce başarısız oluyor"),
   ("taking an ID photo with the default iPhone camera during onboarding",
    "başvuru sırasında varsayılan iPhone kamerasıyla kimlik fotoğrafı çekerken"),
   ("the photo is converted and uploaded, or a clear error is shown",
    "fotoğraf dönüştürülüp yüklenmeli ya da net bir hata gösterilmeli"),
   ("the spinner runs forever and no error appears",
    "yükleme animasyonu sonsuza kadar dönüyor ve hata görünmüyor"),
   "415 Unsupported Media Type image/heic — client does not catch non-2xx", "Major", "mobile"),
 B("limit-not-applied", "Cards", ["limits", "cards"],
   ("monthly spending limit is not enforced for foreign currency purchases",
    "aylık harcama limiti döviz cinsi harcamalarda uygulanmıyor"),
   ("spending above the configured limit in EUR",
    "belirlenen limitin üzerinde EUR cinsinden harcama yaparken"),
   ("the authorisation is declined once the limit is reached",
    "limit dolduktan sonra yetkilendirme reddedilmeli"),
   ("EUR purchases go through regardless of the limit",
    "EUR harcamaları limitten bağımsız olarak geçiyor"),
   "limit check compares txn.amount to limit without FX normalisation", "Major", "backend"),
], epics=[
 E("onboarding-revamp", "Onboarding", ["onboarding", "growth"],
   ("cut the time it takes a new customer to open an account and make a first transfer",
    "yeni müşterinin hesap açıp ilk transferini yapma süresini kısaltmak"),
   ("only 41% of applicants who start onboarding finish it; drop-off peaks at the ID upload step",
    "başvuruyu başlatanların yalnızca %41'i tamamlıyor, en büyük kayıp kimlik yükleme adımında"),
   ("onboarding completion rate", "başvuru tamamlama oranı"),
   "41%", "65%", "Q4",
   (["Auto-fill address fields from the national ID chip",
     "Replace the 4-step form with a 2-step progressive form",
     "Add selfie liveness check with retry guidance",
     "Show a real-time progress indicator with time estimate",
     "Send a resume-application link if the user drops off"],
    ["Kimlik çipinden adres alanlarını otomatik doldurma",
     "4 adımlı formu 2 adımlı aşamalı forma dönüştürme",
     "Yeniden deneme yönlendirmeli selfie canlılık kontrolü ekleme",
     "Tahmini süre gösteren gerçek zamanlı ilerleme göstergesi",
     "Başvuruyu yarım bırakana devam etme linki gönderme"])),
 E("fraud-realtime", "Fraud", ["fraud", "risk"],
   ("detect and stop card fraud in real time instead of in the nightly batch",
    "kart dolandırıcılığını gecelik toplu işle değil gerçek zamanlı tespit edip durdurmak"),
   ("fraud is currently detected 6-18 hours after the fact; average loss per case is 2.400 TL",
    "dolandırıcılık şu anda olaydan 6-18 saat sonra tespit ediliyor, vaka başı ortalama kayıp 2.400 TL"),
   ("average fraud detection latency", "ortalama dolandırıcılık tespit gecikmesi"),
   "9 hours", "under 5 seconds", "H1",
   (["Stream card authorisations to the risk engine over Kafka",
     "Score each authorisation with the ML model in under 200 ms",
     "Push an in-app alert with a one-tap block action",
     "Give analysts a case review queue with decision audit log"],
    ["Kart yetkilendirmelerini Kafka üzerinden risk motoruna aktarma",
     "Her yetkilendirmeyi 200 ms altında ML modeliyle skorlama",
     "Tek dokunuşla bloke aksiyonlu uygulama içi uyarı gönderme",
     "Analistlere karar denetim kayıtlı vaka inceleme kuyruğu sunma"])),
 E("pci-dss-4", "Payments", ["compliance", "security"],
   ("bring the card platform into PCI DSS 4.0 compliance before the audit",
    "kart platformunu denetim öncesinde PCI DSS 4.0 uyumlu hale getirmek"),
   ("the external audit is scheduled for March and 23 controls are currently failing",
    "dış denetim Mart ayında planlandı ve şu anda 23 kontrol başarısız durumda"),
   ("number of failing PCI controls", "başarısız PCI kontrol sayısı"),
   "23", "0", "March audit",
   (["Rotate and vault all payment service credentials",
     "Mask PAN in every log sink and error tracker",
     "Enforce MFA for all production database access",
     "Add automated quarterly access reviews"],
    ["Tüm ödeme servisi kimlik bilgilerini rotasyona alıp kasaya taşıma",
     "Tüm log hedeflerinde ve hata izleyicide PAN maskeleme",
     "Üretim veritabanı erişimlerinde MFA zorunlu kılma",
     "Otomatik çeyreklik erişim incelemesi ekleme"])),
])
