from .core import B, E, F, domain, register

# ---------------------------------------------------------------- E-COMMERCE
d = domain("ecommerce", "e-commerce marketplace", "e-ticaret pazaryeri", "SHOP",
           ["Checkout", "Catalog", "Search", "Cart", "Seller Portal",
            "Returns", "Payments", "Web Frontend"])
register(d, features=[
 F("multi-address", "form", "Checkout", ["checkout", "addresses"],
   ("frequent shopper", "sık alışveriş yapan müşteri"),
   ("save multiple shipping addresses and pick one at checkout",
    "birden fazla teslimat adresi kaydedip ödeme adımında birini seçmek"),
   ("I can send gifts to my family without retyping addresses",
    "adresi her seferinde yeniden yazmadan aileme hediye gönderebileyim"),
   dict(obj_en="saved address", obj_tr="kayıtlı adres",
        surface_en="Checkout step 1", surface_tr="Ödeme 1. adım"), points=5),
 F("guest-checkout", "payment", "Checkout", ["checkout", "conversion"],
   ("first-time visitor", "ilk kez gelen ziyaretçi"),
   ("complete a purchase without creating an account",
    "hesap açmadan alışverişi tamamlamak"),
   ("I can buy quickly without committing to another password",
    "bir şifre daha oluşturmak zorunda kalmadan hızlıca satın alabileyim"),
   dict(obj_en="guest checkout flow", obj_tr="üyeliksiz alışveriş akışı",
        surface_en="Checkout", surface_tr="Ödeme sayfası"), points=8),
 F("facet-filters", "search", "Search", ["search", "filters"],
   ("shopper comparing options", "seçenekleri karşılaştıran müşteri"),
   ("filter search results by brand, price band, rating and delivery speed",
    "arama sonuçlarını marka, fiyat aralığı, puan ve teslimat hızına göre filtrelemek"),
   ("I can narrow 4000 results down to the handful that fit my needs",
    "4000 sonucu ihtiyacıma uyan birkaç ürüne indirebileyim"),
   dict(obj_en="filter panel", obj_tr="filtre paneli",
        surface_en="Search results", surface_tr="Arama sonuçları"), points=8),
 F("back-in-stock", "notify", "Catalog", ["notifications", "catalog"],
   ("shopper who found an out-of-stock item", "tükenmiş ürün bulan müşteri"),
   ("get an email or push when a product is back in stock",
    "ürün tekrar stoğa girdiğinde e-posta veya push bildirimi almak"),
   ("I do not have to keep checking the page every day",
    "her gün sayfayı kontrol etmek zorunda kalmayayım"),
   dict(obj_en="back-in-stock alert", obj_tr="stok bildirimi",
        surface_en="Product page", surface_tr="Ürün sayfası"), points=5),
 F("bulk-price-upload", "upload", "Seller Portal", ["seller", "bulk"],
   ("marketplace seller", "pazaryeri satıcısı"),
   ("update prices and stock for thousands of SKUs with a CSV upload",
    "binlerce SKU'nun fiyat ve stoğunu CSV yükleyerek güncellemek"),
   ("I can run a campaign without editing products one by one",
    "ürünleri tek tek düzenlemeden kampanya başlatabileyim"),
   dict(obj_en="CSV bulk update", obj_tr="CSV toplu güncelleme",
        surface_en="Seller Portal > Products", surface_tr="Satıcı Paneli > Ürünler"), points=13),
 F("return-label", "form", "Returns", ["returns", "logistics"],
   ("customer returning an item", "ürün iade eden müşteri"),
   ("generate a prepaid return label from the order detail page",
    "sipariş detay sayfasından on ödemeli iade etiketi oluşturmak"),
   ("I can drop the parcel off without contacting support",
    "destek ile iletişime geçmeden kargoyu bırakabileyim"),
   dict(obj_en="return label", obj_tr="iade etiketi",
        surface_en="Order detail", surface_tr="Sipariş detayı"), points=8),
 F("wishlist-share", "list", "Catalog", ["wishlist", "social"],
   ("shopper planning a birthday", "doğum günü planlayan müşteri"),
   ("share my wishlist with a private link",
    "istek listemi özel bir linkle paylaşmak"),
   ("my friends can buy the exact items I want",
    "arkadaşlarım tam olarak istediğim ürünleri alabilsin"),
   dict(obj_en="shareable wishlist", obj_tr="paylaşılabilir istek listesi",
        surface_en="Wishlist", surface_tr="İstek listem"), points=5),
 F("seller-payout-report", "report", "Seller Portal", ["seller", "reporting"],
   ("seller doing monthly accounting", "aylık muhasebesini yapan satıcı"),
   ("download a payout report showing commissions, refunds and net transfer",
    "komisyon, iade ve net transferi gösteren hakediş raporu indirmek"),
   ("I can reconcile marketplace income with my books in minutes",
    "pazaryeri gelirini defterlerimle dakikalar içinde eşleştirebileyim"),
   dict(obj_en="payout report", obj_tr="hakediş raporu",
        surface_en="Seller Portal > Finance", surface_tr="Satıcı Paneli > Finans"), points=8),
], bugs=[
 B("cart-clear-login", "Cart", ["cart", "session"],
   ("the cart is emptied when a guest logs in during checkout",
    "ödeme sırasında giriş yapan misafir kullanıcının sepeti boşalıyor"),
   ("adding items as a guest, then signing in at the payment step",
    "misafir olarak ürün ekleyip ödeme adımında giriş yaparken"),
   ("guest cart items are merged into the account cart",
    "misafir sepeti hesap sepetiyle birleştirilmeli"),
   ("the cart is replaced by the (empty) account cart and items are lost",
    "sepet, boş olan hesap sepetiyle değiştiriliyor ve ürünler kayboluyor"),
   "session merge skipped: cart_token rotated before merge_guest_cart() runs", "Critical", "backend"),
 B("price-vat", "Checkout", ["pricing", "vat"],
   ("VAT is calculated on the discounted price for some campaigns but not others",
    "bazı kampanyalarda KDV indirimli fiyat üzerinden, bazılarında değil hesaplanıyor"),
   ("applying a percentage coupon to an order with mixed VAT rates",
    "farklı KDV oranlı ürünler içeren siparişe yüzde kuponu uygularken"),
   ("VAT is always computed on the post-discount line total",
    "KDV her zaman indirim sonrası satır toplamı üzerinden hesaplanmalı"),
   ("orders with mixed rates are overcharged by up to 3 TL",
    "farklı oranlı siparişlerde 3 TL'ye kadar fazla tahsilat yapılıyor"),
   "PriceEngine applies discount after tax for coupon_type=PERCENT_CART", "Critical", "backend"),
 B("search-turkish-chars", "Search", ["search", "i18n"],
   ("searching with Turkish characters returns no results",
    "Türkçe karakterle yapılan arama sonuç döndürmüyor"),
   ("searching for 'sutyen' or 'gomlek' with correct Turkish spelling",
    "'sutyen' veya 'gomlek' kelimelerini doğru Türkçe yazımla ararken"),
   ("results match regardless of diacritics",
    "sonuçlar aksan işaretlerinden bağımsız eşleşmeli"),
   ("0 results are returned while the ASCII spelling works",
    "ASCII yazım çalışırken 0 sonuç dönüyor"),
   "ES analyzer missing asciifolding filter on product_name.tr field", "Major", "backend"),
 B("stock-oversell", "Catalog", ["inventory", "race-condition"],
   ("the last unit of a product can be sold to two customers at once",
    "bir ürünün son adedi aynı anda iki müşteriye satılabiliyor"),
   ("two customers completing checkout for the same SKU within the same second",
    "iki müşteri aynı SKU için aynı saniye içinde ödemeyi tamamladığında"),
   ("the second checkout fails with an out-of-stock error",
    "ikinci ödeme stok yetersiz hatasıyla başarısız olmalı"),
   ("both orders are created and one is cancelled manually a day later",
    "iki sipariş de oluşuyor ve biri bir gün sonra elle iptal ediliyor"),
   "stock decrement is read-then-write without SELECT FOR UPDATE", "Critical", "backend"),
 B("mobile-filter-scroll", "Web Frontend", ["mobile", "ux"],
   ("the filter panel resets scroll position to the top on every selection",
    "filtre paneli her seçimde kaydırma konumunu en başa donduruyor"),
   ("selecting a third or fourth filter on a mobile browser",
    "mobil tarayıcıda üçüncü veya dördüncü filtreyi seçerken"),
   ("scroll position is preserved after the result count updates",
    "sonuç sayısı güncellendikten sonra kaydırma konumu korunmalı"),
   ("the user is thrown back to the top and has to scroll again",
    "kullanıcı en başa fırlatılıyor ve tekrar kaydırmak zorunda kalıyor"),
   "full list re-render on state change; no key stability in FilterList", "Minor", "frontend"),
 B("csv-encoding", "Seller Portal", ["import", "encoding"],
   ("Turkish characters in bulk CSV uploads are stored as question marks",
    "toplu CSV yüklemelerinde Türkçe karakterler soru işareti olarak kaydediliyor"),
   ("uploading a CSV exported from Excel with Turkish product names",
    "Excel'den dışarı aktarılmış, Türkçe ürün adlı bir CSV yüklerken"),
   ("product names are stored exactly as written",
    "ürün adları yazıldığı gibi kaydedilmeli"),
   ("'Gomlek' becomes 'G?mlek' in the catalog and in search",
    "'Gomlek' katalogda ve aramada 'G?mlek' oluyor"),
   "reader assumes UTF-8; Excel exports windows-1254 without BOM", "Major", "backend"),
], epics=[
 E("checkout-conversion", "Checkout", ["conversion", "checkout"],
   ("reduce checkout abandonment on mobile",
    "mobilde ödeme adımındakı terk oranını düşürmek"),
   ("68% of mobile users who reach the payment step leave before paying; the form has 14 required fields",
    "ödeme adımına ulaşan mobil kullanıcıların %68'i ödeme yapmadan ayrılıyor, formda 14 zorunlu alan var"),
   ("mobile checkout abandonment rate", "mobil ödeme terk oranı"),
   "68%", "45%", "Q3",
   (["Add guest checkout with post-purchase account creation",
     "Reduce the address form to 5 fields with autocomplete",
     "Add Apple Pay and Google Pay one-tap payment",
     "Show delivery date and total cost before the payment step",
     "Recover abandoned carts with a reminder email after 4 hours"],
    ["Satın alma sonrası hesap oluşturmalı üyeliksiz alışveriş ekleme",
     "Adres formunu otomatik tamamlamayla 5 alana indirme",
     "Apple Pay ve Google Pay ile tek dokunuşla ödeme ekleme",
     "Ödeme adımından önce teslimat tarihi ve toplam tutarı gösterme",
     "Terk edilen sepetleri 4 saat sonra hatırlatma e-postasıyla geri kazanma"])),
 E("search-relevance", "Search", ["search", "relevance"],
   ("make search return the right product in the first five results",
    "aramanın doğru ürünü ilk beş sonuçta getirmesini sağlamak"),
   ("31% of searches end with no click; the top query 'telefon kilifi' returns accessories for the wrong models",
    "aramaların %31'i tıklama olmadan bitiyor, en çok aranan 'telefon kılıfı' yanlış modellerin aksesuarlarını getiriyor"),
   ("search click-through rate", "arama tıklama oranı"),
   "69%", "85%", "Q4",
   (["Add Turkish language analyzer with asciifolding and stemming",
     "Boost by conversion rate and in-stock status",
     "Add did-you-mean suggestions for misspelled queries",
     "Log zero-result queries into a merchandising dashboard"],
    ["asciifolding ve gövdeleme içeren Türkçe dil analizörü ekleme",
     "Dönüşüm oranı ve stok durumuna göre sıralamayı güçlendirme",
     "Yanlış yazılan sorgular için 'bunu mu demek istediniz' önerisi",
     "Sıfır sonuçlu sorguları merchandising panosuna kaydetme"])),
])

# ---------------------------------------------------------------- B2B SAAS
d = domain("saas", "B2B SaaS work management product", "B2B SaaS iş yönetimi ürünü", "WM",
           ["Workspace", "Permissions", "Billing", "Integrations", "Reporting",
            "Automation", "API", "Admin Console"])
register(d, features=[
 F("sso-scim", "auth", "Admin Console", ["sso", "enterprise"],
   ("IT administrator at a customer company", "müşteri şirkette çalışan BT yöneticisi"),
   ("provision and deprovision users automatically through SCIM",
    "kullanıcıları SCIM üzerinden otomatik olarak açıp kapatmak"),
   ("leavers lose access the same day without a manual checklist",
    "işten ayrılanlar elle kontrol listesi olmadan aynı gün erişimini kaybetsin"),
   dict(obj_en="SCIM provisioning", obj_tr="SCIM kullanıcı sağlama",
        surface_en="Admin Console > Identity", surface_tr="Yönetim Konsolu > Kimlik"), points=13),
 F("granular-roles", "permission", "Permissions", ["rbac", "enterprise"],
   ("workspace owner", "çalışma alanı sahibi"),
   ("assign per-project roles instead of a single workspace-wide role",
    "tek bir çalışma alanı rolü yerine proje bazında rol atamak"),
   ("contractors only see the projects they are hired for",
    "dış kaynak çalışanlar yalnızca çalıştıkları projeleri görsün"),
   dict(obj_en="project role", obj_tr="proje rolü",
        surface_en="Project settings > Members", surface_tr="Proje ayarları > Üyeler"), points=13),
 F("usage-billing", "payment", "Billing", ["billing", "self-service"],
   ("finance manager on the customer side", "müşteri tarafındakı finans yöneticisi"),
   ("see a live breakdown of seat usage and overage charges",
    "koltuk kullanımını ve aşım ücretlerini canlı döküm halinde görmek"),
   ("there are no surprises on the invoice at the end of the month",
    "ay sonunda faturada sürpriz olmasın"),
   dict(obj_en="usage breakdown", obj_tr="kullanım dökümü",
        surface_en="Billing > Usage", surface_tr="Faturalandırma > Kullanım"), points=8),
 F("slack-notify", "integration", "Integrations", ["slack", "notifications"],
   ("team lead", "takım lideri"),
   ("route task assignments and due-date reminders to a Slack channel",
    "görev atamalarını ve termin hatırlatmalarını bir Slack kanalına yönlendirmek"),
   ("my team sees updates where they already work",
    "ekibim güncellemeleri zaten çalıştıkları yerde görsün"),
   dict(obj_en="Slack integration", obj_tr="Slack entegrasyonu",
        surface_en="Integrations page", surface_tr="Entegrasyonlar sayfası"), points=8),
 F("saved-views", "list", "Workspace", ["views", "productivity"],
   ("project manager", "proje yöneticisi"),
   ("save a filtered board view and share it with the team",
    "filtrelenmiş bir pano görünümünü kaydedip ekiple paylaşmak"),
   ("everyone opens the same view instead of rebuilding filters",
    "herkes filtreleri baştan kurmak yerine aynı görünümü açsın"),
   dict(obj_en="saved view", obj_tr="kayıtlı görünüm",
        surface_en="Board toolbar", surface_tr="Pano araç cubugu"), points=5),
 F("audit-log-export", "export", "Admin Console", ["audit", "compliance"],
   ("security officer", "güvenlik sorumlusu"),
   ("export an audit log of permission changes for a date range",
    "belirli bir tarih aralığındakı yetki değişikliklerinin denetim kaydını dışa aktarmak"),
   ("I can answer auditor questions without opening a support ticket",
    "destek talebi açmadan denetçi sorularını yanıtlayabileyim"),
   dict(obj_en="audit log export", obj_tr="denetim kaydı dışa aktarımı",
        surface_en="Admin Console > Security", surface_tr="Yönetim Konsolu > Güvenlik"), points=8),
 F("automation-rules", "form", "Automation", ["automation", "workflow"],
   ("operations lead", "operasyon lideri"),
   ("build if-this-then-that rules that move tasks between columns",
    "görevleri sütunlar arasında taşıyan kural bazlı otomasyonlar kurmak"),
   ("routine status updates happen without anyone dragging cards",
    "rutin durum güncellemeleri kimse kart sürüklemeden gerçekleşsin"),
   dict(obj_en="automation rule", obj_tr="otomasyon kuralı",
        surface_en="Automation builder", surface_tr="Otomasyon oluşturucu"), points=13),
 F("api-rate-headers", "integration", "API", ["api", "dx"],
   ("integration developer", "entegrasyon geliştiricisi"),
   ("see remaining quota and reset time in rate-limit response headers",
    "kalan kotayı ve sıfırlanma zamanını hız limiti yanıt başlıklarında görmek"),
   ("my integration can back off instead of getting blocked",
    "entegrasyonum engellenmek yerine hızını kendisi düşürebilsin"),
   dict(obj_en="rate limit headers", obj_tr="hız limiti başlıkları",
        surface_en="Public REST API", surface_tr="Genel REST API"), points=3),
], bugs=[
 B("role-escalation", "Permissions", ["security", "rbac"],
   ("a project viewer can edit tasks through the public API",
    "proje izleyicisi genel API üzerinden görevleri düzenleyebiliyor"),
   ("calling PATCH /v1/tasks/{id} with a viewer-scoped token",
    "izleyici kapsamlı bir token ile PATCH /v1/tasks/{id} çağrıldığında"),
   ("the API returns 403 Forbidden",
    "API 403 Forbidden dondurmalı"),
   ("the task is updated and returns 200 OK",
    "görev güncelleniyor ve 200 OK dönüyor"),
   "permission check exists in web controller only; API handler skips can_edit()", "Critical", "backend"),
 B("seat-count-drift", "Billing", ["billing", "data"],
   ("invoiced seat count is higher than the number of active users",
    "faturalandırılan koltuk sayısı aktif kullanıcı sayısından fazla"),
   ("deactivating users mid-cycle and viewing the next invoice",
    "dönem ortasında kullanıcı pasifleştirip sonraki faturayı görüntülerken"),
   ("deactivated users are excluded from the next billing period",
    "pasifleştirilen kullanıcılar sonraki fatura döneminden çıkarılmalı"),
   ("deactivated users are billed for one extra cycle",
    "pasifleştirilen kullanıcılar bir dönem daha faturalandırılıyor"),
   "billing snapshot taken at period start, ignores mid-cycle deactivation events", "Major", "data"),
 B("webhook-retry-storm", "Integrations", ["webhooks", "reliability"],
   ("a failing customer webhook endpoint receives thousands of retries per hour",
    "hata veren müşteri webhook adresi saatte binlerce yeniden deneme alıyor"),
   ("a customer endpoint returning 500 for more than 10 minutes",
    "müşteri adresi 10 dakikadan uzun süre 500 dondurduğunda"),
   ("retries back off exponentially and stop after 24 hours",
    "yeniden denemeler üstel olarak seyrelmeli ve 24 saat sonra durmalı"),
   ("retries fire every 30 seconds indefinitely and the customer is rate-limited by their own WAF",
    "yeniden denemeler her 30 saniyede bir sonsuza kadar tetikleniyor ve müşteri kendi WAF'i tarafından engelleniyor"),
   "retry policy uses fixed delay; dead-letter queue never consumed", "Major", "backend"),
 B("saved-view-share", "Workspace", ["views", "permissions"],
   ("a shared saved view shows tasks the recipient is not allowed to see",
    "paylaşılan kayıtlı görünüm, alıcıya görme yetkisi olmayan görevleri gösteriyor"),
   ("opening a saved view shared by a member of a restricted project",
    "kısıtlı bir projenin üyesi tarafından paylaşılan kayıtlı görünümü açarken"),
   ("results are re-filtered against the viewer's own permissions",
    "sonuçlar görüntüleyenin kendi yetkilerine göre yeniden filtrelenmeli"),
   ("task titles and assignees from the restricted project are visible",
    "kısıtlı projedeki görev başlıkları ve atanan kişiler görünüyor"),
   "view results are cached per view_id, not per (view_id, user_id)", "Critical", "backend"),
 B("automation-loop", "Automation", ["automation", "reliability"],
   ("two automation rules trigger each other in an infinite loop",
    "iki otomasyon kuralı birbirini sonsuz döngüye sokuyor"),
   ("creating a rule that sets a label and another that reacts to that label",
    "etiket atayan bir kural ve o etikete tepki veren başka bir kural oluşturulduğunda"),
   ("the engine detects the cycle and disables the rule with a warning",
    "motor döngüyü tespit edip kuralı uyarıyla devre dışı bırakmalı"),
   ("the task accumulates 12.000 activity entries in an hour",
    "görev bir saatte 12.000 aktivite kaydı biriktiriyor"),
   "no execution depth counter or loop detection in RuleExecutor", "Major", "backend"),
 B("timezone-due", "Workspace", ["timezone", "ux"],
   ("due-date reminders arrive a day early for users in UTC+ timezones",
    "termin hatırlatmaları UTC+ saat dilimindeki kullanıcılara bir gün erken geliyor"),
   ("setting a due date of 'tomorrow' as a user in Istanbul",
    "İstanbul'dakı bir kullanıcı termini 'yarın' olarak ayarladığında"),
   ("the reminder fires on the morning of the due date in the user's timezone",
    "hatırlatma, kullanıcının saat diliminde termin günü sabahı tetiklenmeli"),
   ("the reminder arrives the previous evening at 21:00",
    "hatırlatma bir önceki akşam 21:00'da geliyor"),
   "scheduler stores due_date as date, renders reminder at 00:00 UTC", "Minor", "backend"),
], epics=[
 E("enterprise-readiness", "Admin Console", ["enterprise", "security"],
   ("close the security and identity gaps that block enterprise deals",
    "kurumsal anlaşmaları engelleyen güvenlik ve kimlik eksiklerini kapatmak"),
   ("we lost 4 of the last 7 enterprise deals on the security questionnaire; SSO, SCIM and audit export were the blockers",
    "son 7 kurumsal anlaşmanın 4'unu güvenlik anketinde kaybettik, engeller SSO, SCIM ve denetim dışa aktarımıydı"),
   ("enterprise deals lost on security review", "güvenlik incelemesinde kaybedilen kurumsal anlaşma"),
   "4 of 7", "0 of 10", "H1",
   (["Add SAML 2.0 SSO with IdP-initiated login",
     "Add SCIM 2.0 user and group provisioning",
     "Add per-project role based access control",
     "Add exportable audit log with 12 month retention",
     "Publish a SOC 2 Type II readiness page"],
    ["IdP başlatmalı giriş destekli SAML 2.0 SSO ekleme",
     "SCIM 2.0 kullanıcı ve grup sağlama ekleme",
     "Proje bazında rol tabanlı erişim kontrolü ekleme",
     "12 ay saklamalı, dışa aktarılabilir denetim kaydı ekleme",
     "SOC 2 Type II hazırlık sayfası yayınlama"])),
 E("activation-30d", "Workspace", ["activation", "growth"],
   ("get new workspaces to their first collaborative win within a week",
    "yeni çalışma alanlarını bir hafta içinde ilk ortak başarıya ulaştırmak"),
   ("only 22% of new workspaces have three or more active users after 30 days",
    "yeni çalışma alanlarının yalnızca %22'sinde 30 gün sonra üç veya daha fazla aktif kullanıcı var"),
   ("30-day workspace activation rate", "30 günlük çalışma alanı aktivasyon oranı"),
   "22%", "40%", "Q4",
   (["Add a guided setup checklist with three starter templates",
     "Add bulk teammate invite by email domain",
     "Send a nudge email when a workspace has one user after 3 days",
     "Add an in-product tour for the board and automation builder"],
    ["Üç başlangıç şablonlu rehberli kurulum kontrol listesi ekleme",
     "E-posta alan adına göre toplu takım arkadaşı daveti ekleme",
     "3 gün sonra tek kullanıcılı çalışma alanlarına dürtme e-postası gönderme",
     "Pano ve otomasyon oluşturucu için ürün içi tür ekleme"])),
])
