from .core import B, E, F, domain, register

# ---------------------------------------------------------------- HEALTHCARE
d = domain("health", "telehealth and clinic booking platform", "tele-tip ve klinik randevu platformu", "MED",
           ["Appointments", "Patient Records", "Video Visit", "Prescriptions",
            "Billing", "Provider Portal", "Mobile App"])
register(d, features=[
 F("slot-booking", "form", "Appointments", ["booking", "patient"],
   ("patient looking for a specialist", "uzman hekim arayan hasta"),
   ("see a doctor's real available slots and book one without calling",
    "bir doktorun gerçek müsait saatlerini görüp telefon etmeden randevu almak"),
   ("I can book an appointment outside clinic opening hours",
    "klinik çalışma saatleri dışında da randevu alabileyim"),
   dict(obj_en="appointment slot", obj_tr="randevu saati",
        surface_en="Doctor profile", surface_tr="Doktor profili"), points=8),
 F("visit-reminder", "notify", "Appointments", ["reminders", "no-show"],
   ("patient with an upcoming visit", "yaklaşan randevusu olan hasta"),
   ("receive an SMS and push reminder 24 hours and 1 hour before my visit",
    "randevumdan 24 saat ve 1 saat önce SMS ve push hatırlatma almak"),
   ("I do not miss the appointment and lose the fee",
    "randevuyu kaçırıp ücreti kaybetmeyeyim"),
   dict(obj_en="visit reminder", obj_tr="randevu hatırlatması",
        surface_en="Notification service", surface_tr="Bildirim servisi"), points=5),
 F("video-waiting-room", "realtime", "Video Visit", ["video", "telehealth"],
   ("patient joining a video visit", "görüntülü muayeneye katılan hasta"),
   ("wait in a virtual waiting room that shows my place in the queue",
    "sıradaki yerimi gösteren sanal bekleme odasında beklemek"),
   ("I know whether to keep waiting or reschedule",
    "beklemeye devam mi edeceğimi yoksa randevuyu erteleyeceğimi bileyim"),
   dict(obj_en="waiting room", obj_tr="bekleme odası",
        surface_en="Video visit screen", surface_tr="Görüntülü muayene ekranı"), points=8),
 F("e-prescription", "integration", "Prescriptions", ["prescription", "integration"],
   ("physician finishing a consultation", "muayeneyi bitiren hekim"),
   ("send an e-prescription to the national system without leaving the visit screen",
    "muayene ekranından çıkmadan ulusal sisteme e-reçete göndermek"),
   ("the patient can collect medication straight from any pharmacy",
    "hasta ilacı doğrudan herhangi bir eczaneden alabilsin"),
   dict(obj_en="e-prescription", obj_tr="e-reçete",
        surface_en="Visit summary", surface_tr="Muayene özeti"), points=13),
 F("record-timeline", "list", "Patient Records", ["records", "clinical"],
   ("physician preparing for a visit", "muayeneye hazırlanan hekim"),
   ("see the patient's visits, lab results and prescriptions on one timeline",
    "hastanın muayene, tahlil ve reçetelerini tek bir zaman çizelgesinde görmek"),
   ("I can understand the case in two minutes instead of ten",
    "vakayı on dakika yerine iki dakikada anlayabileyim"),
   dict(obj_en="patient timeline", obj_tr="hasta zaman çizelgesi",
        surface_en="Patient record", surface_tr="Hasta kaydı"), points=8),
 F("consent-capture", "form", "Patient Records", ["consent", "kvkk"],
   ("patient starting treatment", "tedaviye başlayan hasta"),
   ("read and digitally sign the treatment consent form on my phone",
    "tedavi onam formunu telefonumdan okuyup dijital olarak imzalamak"),
   ("I do not have to arrive 20 minutes early to sign paperwork",
    "evrak imzalamak için 20 dakika erken gelmek zorunda kalmayayım"),
   dict(obj_en="digital consent form", obj_tr="dijital onam formu",
        surface_en="Pre-visit checklist", surface_tr="Muayene öncesi kontrol listesi"), points=8),
], bugs=[
 B("double-booking", "Appointments", ["booking", "race-condition"],
   ("the same slot can be booked by two patients simultaneously",
    "aynı randevu saati iki hasta tarafından eş zamanlı alınabiliyor"),
   ("two patients confirming the same 10:30 slot within the same second",
    "iki hasta aynı 10:30 randevusunu aynı saniye içinde onayladığında"),
   ("the second booking fails with a slot-taken message",
    "ikinci randevu 'saat dolu' mesajıyla başarısız olmalı"),
   ("both bookings are confirmed and the clinic calls one patient to cancel",
    "iki randevu da onaylanıyor ve klinik bir hastayı arayıp iptal ediyor"),
   "availability check and insert are not in one transaction; no unique index on (doctor_id, start_at)", "Critical", "backend"),
 B("record-cross-tenant", "Patient Records", ["security", "privacy"],
   ("a physician can open a patient record from another clinic via direct URL",
    "bir hekim doğrudan URL ile başka bir kliniğin hasta kaydını açabiliyor"),
   ("changing the patient id in the record URL",
    "kayıt adresindeki hasta kimliğini değiştirerek"),
   ("the request is rejected with 403 and logged as an access violation",
    "istek 403 ile reddedilmeli ve erişim ihlali olarak loglanmalı"),
   ("the full record including lab results is rendered",
    "tahlil sonuçları dahil kaydın tamamı görüntüleniyor"),
   "no clinic_id scoping in PatientRecordController#show (IDOR)", "Critical", "backend"),
 B("video-audio-android", "Video Visit", ["mobile", "android", "video"],
   ("audio drops after switching from Wi-Fi to mobile data during a visit",
    "muayene sırasında Wi-Fi'dan mobil veriye geçince ses kesiliyor"),
   ("walking out of Wi-Fi range while in an active video visit on Android",
    "Android'de aktif görüntülü muayenedeyken Wi-Fi kapsamından çıkarken"),
   ("the session renegotiates ICE and audio resumes within 3 seconds",
    "oturum ICE yeniden pazarlığı yapmalı ve ses 3 saniye içinde geri gelmeli"),
   ("video continues but audio never returns until both sides rejoin",
    "görüntü devam ediyor ama iki taraf da yeniden katılana kadar ses geri gelmiyor"),
   "ICE restart not triggered on network change; PeerConnection stays in 'failed'", "Major", "mobile"),
 B("reminder-sent-cancelled", "Appointments", ["reminders", "data"],
   ("reminders are still sent for cancelled appointments",
    "iptal edilen randevular için hatırlatma gönderilmeye devam ediyor"),
   ("cancelling an appointment less than 24 hours before it starts",
    "randevuyu başlangıçından 24 saatten kısa süre önce iptal ederken"),
   ("queued reminders for that appointment are cancelled too",
    "o randevuya ait kuyruktakı hatırlatmalar da iptal edilmeli"),
   ("the patient receives a reminder for a visit they already cancelled",
    "hasta iptal ettiği randevu için hatırlatma alıyor"),
   "reminder jobs scheduled at booking time; cancellation does not dequeue them", "Minor", "backend"),
 B("prescription-dose-unit", "Prescriptions", ["clinical", "data"],
   ("dosage unit is dropped when a prescription is printed",
    "reçete yazdırıldığında doz birimi kayboluyor"),
   ("printing a prescription that uses mg/ml dosing",
    "mg/ml dozlamalı bir reçeteyi yazdırırken"),
   ("the printed prescription shows the full dose with its unit",
    "yazdırılan reçetede doz birimiyle birlikte tam gösterilmeli"),
   ("the printout shows '5' with no unit, which the pharmacy has to phone about",
    "çıktıda birimsiz '5' yazıyor ve eczane telefonla teyit ediyor"),
   "PDF template binds dose.value but not dose.unit", "Critical", "frontend"),
], epics=[
 E("no-show-reduction", "Appointments", ["no-show", "operations"],
   ("reduce appointment no-shows across the clinic network",
    "klinik ağı genelinde randevuya gelmeme oranını düşürmek"),
   ("18% of booked appointments are no-shows, costing an estimated 3,1M TL of idle clinician time per year",
    "alınan randevuların %18'i gerçekleşmiyor, bu yılda tahmini 3,1M TL boş hekim zamanı demek"),
   ("appointment no-show rate", "randevuya gelmeme oranı"),
   "18%", "9%", "Q4",
   (["Send layered SMS and push reminders at 24h and 1h",
     "Let patients reschedule in one tap from the reminder",
     "Offer freed slots to a waiting list automatically",
     "Show a no-show risk score to reception for overbooking decisions"],
    ["24 saat ve 1 saat öncesinde katmanlı SMS ve push hatırlatma gönderme",
     "Hastaların hatırlatmadan tek dokunuşla randevu ertelemesini sağlama",
     "Boşalan saatleri otomatik olarak bekleme listesine sunma",
     "Resepsiyona fazla rezervasyon kararı için gelmeme risk skoru gösterme"])),
])

# ---------------------------------------------------------------- LOGISTICS
d = domain("logistics", "parcel delivery and fleet platform", "kargo teslimat ve filo platformu", "LOG",
           ["Tracking", "Dispatch", "Courier App", "Warehouse", "Customer Portal",
            "Routing", "Integrations"])
register(d, features=[
 F("live-tracking", "realtime", "Tracking", ["tracking", "customer"],
   ("recipient waiting for a parcel", "kargosunu bekleyen alıcı"),
   ("watch the courier's live position and estimated arrival on a map",
    "kuryenin canlı konumunu ve tahmini varış saatini harita üzerinde izlemek"),
   ("I do not have to stay home all day",
    "bütün gün evde beklemek zorunda kalmayayım"),
   dict(obj_en="live tracking map", obj_tr="canlı takip haritası",
        surface_en="Tracking page", surface_tr="Takip sayfası"), points=13),
 F("delivery-window", "form", "Customer Portal", ["delivery", "self-service"],
   ("recipient with a fixed schedule", "programı sabit olan alıcı"),
   ("choose a two-hour delivery window the evening before",
    "bir önceki akşam iki saatlik teslimat aralığı seçmek"),
   ("the parcel arrives when I am actually at home",
    "kargo gerçekten evde olduğum saatte gelsin"),
   dict(obj_en="delivery window", obj_tr="teslimat aralığı",
        surface_en="Customer portal", surface_tr="Müşteri portalı"), points=8),
 F("proof-of-delivery", "upload", "Courier App", ["pod", "courier"],
   ("courier completing a drop", "teslimatı tamamlayan kurye"),
   ("capture a photo and signature as proof of delivery in one screen",
    "teslimat kanıtı olarak fotoğraf ve imzayı tek ekranda almak"),
   ("delivery disputes can be closed with evidence in seconds",
    "teslimat itirazları kanıtla saniyeler içinde kapatılabilsin"),
   dict(obj_en="proof of delivery", obj_tr="teslimat kanıtı",
        surface_en="Courier app > Stop detail", surface_tr="Kurye uygulaması > Durak detayı"), points=8),
 F("route-optimize", "report", "Routing", ["routing", "efficiency"],
   ("dispatch planner", "sevkiyat planlayıcısı"),
   ("generate an optimised route order for each courier before the shift",
    "vardiya öncesi her kurye için optimize edilmiş durak sırası oluşturmak"),
   ("couriers drive fewer kilometres and finish earlier",
    "kuryeler daha az kilometre yapıp daha erken bitirsin"),
   dict(obj_en="optimised route", obj_tr="optimize rota",
        surface_en="Dispatch console", surface_tr="Sevkiyat konsolu"), points=13),
 F("failed-attempt-reason", "form", "Courier App", ["courier", "data-quality"],
   ("courier who could not deliver", "teslimat yapamayan kurye"),
   ("select a structured reason code instead of typing free text",
    "serbest metin yazmak yerine yapılandırılmış bir sebep kodu seçmek"),
   ("operations can see why deliveries fail and fix the top causes",
    "operasyon teslimatların neden başarısız olduğunu görüp en sık sebepleri çözebilsin"),
   dict(obj_en="failure reason code", obj_tr="başarısızlık sebep kodu",
        surface_en="Courier app > Failed attempt", surface_tr="Kurye uygulaması > Başarısız teslimat"), points=5),
 F("bulk-label", "export", "Warehouse", ["warehouse", "bulk"],
   ("warehouse operator", "depo operatörü"),
   ("print shipping labels for a whole pallet in one batch",
    "bir paletin tamamının kargo etiketlerini tek seferde yazdırmak"),
   ("dispatch is not blocked by printing labels one by one",
    "sevkiyat etiketleri tek tek yazdırmak yüzünden beklemesin"),
   dict(obj_en="bulk label printing", obj_tr="toplu etiket yazdırma",
        surface_en="Warehouse console", surface_tr="Depo konsolu"), points=5),
], bugs=[
 B("gps-drift-tunnel", "Tracking", ["gps", "mobile"],
   ("courier position jumps hundreds of metres after tunnels",
    "tünel çıkışlarında kurye konumu yüzlerce metre sıçrıyor"),
   ("driving through a tunnel with the courier app in the background",
    "kurye uygulaması arka plandayken tünelden geçerken"),
   ("positions with low accuracy are discarded and the track is smoothed",
    "düşük doğruluklu konumlar atılmalı ve iz düzeltilmeli"),
   ("the customer map shows the courier crossing the Bosphorus and back",
    "müşteri haritasında kurye Boğaz'ı geçip geri dönüyor gibi görünüyor"),
   "no accuracy threshold filter on CLLocation updates (horizontalAccuracy > 500m accepted)", "Minor", "mobile"),
 B("eta-negative", "Tracking", ["eta", "frontend"],
   ("the ETA shows a negative value once the courier is late",
    "kurye geçikince tahmini varış süresi negatif görünüyor"),
   ("viewing tracking after the promised delivery window has passed",
    "vaat edilen teslimat aralığı geçtikten sonra takip sayfasına bakarken"),
   ("the UI shows 'delayed' with a recalculated estimate",
    "arayüz yeniden hesaplanmış tahminle 'gecikti' göstermeli"),
   ("the UI shows 'Arriving in -37 minutes'",
    "arayüz 'Tahmini varış: -37 dakika' gösteriyor"),
   "ETA = window_end - now without clamping or recompute", "Minor", "frontend"),
 B("pod-photo-loss", "Courier App", ["upload", "offline"],
   ("proof-of-delivery photos are lost when the courier is offline",
    "kurye çevrimdışıyken teslimat kanıtı fotoğrafları kayboluyor"),
   ("completing a delivery in a basement with no signal",
    "sinyal olmayan bir bodrum katında teslimat tamamlanırken"),
   ("the photo is queued locally and uploaded when connectivity returns",
    "fotoğraf yerelde kuyruğa alınıp bağlantı gelince yüklenmeli"),
   ("the delivery is marked complete but the photo is gone",
    "teslimat tamamlandı olarak işaretleniyor ama fotoğraf yok oluyor"),
   "upload attempted once in-memory; no persistent outbox queue", "Major", "mobile"),
 B("route-loop", "Routing", ["routing", "algorithm"],
   ("optimised routes send couriers past the same street three times",
    "optimize rotalar kuryeleri aynı sokaktan üç kez geçiriyor"),
   ("optimising a route with more than 80 stops",
    "80'den fazla durağı olan bir rotayı optimize ederken"),
   ("each street segment is visited once unless capacity forces a return",
    "kapasite zorlamadıkça her sokak parçası bir kez ziyaret edilmeli"),
   ("total distance is 22% higher than the manual plan",
    "toplam mesafe elle yapılan plandan %22 daha uzun çıkıyor"),
   "solver time budget 2s exceeded, falls back to nearest-neighbour without 2-opt", "Major", "backend"),
 B("barcode-dup", "Warehouse", ["barcode", "data"],
   ("scanning a barcode twice creates a duplicate parcel record",
    "bir barkodu iki kez okutmak mükerrer kargo kaydı oluşturuyor"),
   ("scanning the same parcel at intake and again at sorting",
    "aynı kargoyu kabulde ve tekrar ayırmada okuturken"),
   ("the second scan updates the existing record's status",
    "ikinci okutma mevcut kaydın durumunu güncellemeli"),
   ("a second parcel with the same tracking number is created",
    "aynı takip numarasıyla ikinci bir kargo kaydı oluşuyor"),
   "no unique constraint on tracking_number; upsert not used", "Major", "data"),
], epics=[
 E("first-attempt-delivery", "Tracking", ["operations", "cx"],
   ("increase the share of parcels delivered on the first attempt",
    "ilk denemede teslim edilen kargo oranını artırmak"),
   ("only 74% of parcels are delivered on the first attempt; each retry costs 42 TL and delays the customer by two days",
    "kargoların yalnızca %74'u ilk denemede teslim ediliyor, her tekrar deneme 42 TL maliyet ve müşteriye iki gün gecikme demek"),
   ("first-attempt delivery rate", "ilk denemede teslim oranı"),
   "74%", "88%", "Q3",
   (["Let recipients pick a two-hour delivery window",
     "Send a live tracking link 30 minutes before arrival",
     "Add safe-place and neighbour delivery consent options",
     "Capture structured failure reasons and surface the top causes weekly"],
    ["Alıcıların iki saatlik teslimat aralığı seçmesini sağlama",
     "Varıştan 30 dakika önce canlı takip linki gönderme",
     "Güvenli yer ve komşuya teslim onay seçenekleri ekleme",
     "Yapılandırılmış başarısızlık sebeplerini toplayıp en sık sebepleri haftalık raporlama"])),
])

# ---------------------------------------------------------------- EDTECH
d = domain("edtech", "online learning platform", "çevrimiçi eğitim platformu", "EDU",
           ["Course Player", "Assessments", "Instructor Tools", "Enrollment",
            "Certificates", "Mobile App", "Analytics"])
register(d, features=[
 F("offline-download", "upload", "Mobile App", ["offline", "mobile"],
   ("student with limited data", "kısıtlı internet kotası olan öğrenci"),
   ("download lessons for offline viewing and have progress sync later",
    "dersleri çevrimdışı izlemek üzere indirmek ve ilerlemem sonra senkronize olsun"),
   ("I can study on the metro without using my data plan",
    "metroda kotamı harcamadan çalışabileyim"),
   dict(obj_en="offline download", obj_tr="çevrimdışı indirme",
        surface_en="Lesson list", surface_tr="Ders listesi"), points=13),
 F("quiz-retry-policy", "form", "Assessments", ["assessment", "policy"],
   ("instructor designing an assessment", "değerlendirme tasarlayan eğitmen"),
   ("configure how many retries a quiz allows and whether the best or last score counts",
    "bir sınavın kaç tekrar hakkı vereceğini ve en iyi mi son puanın mi sayılacağını ayarlamak"),
   ("assessment rules match my course policy without emailing support",
    "değerlendirme kuralları destek ile yazışmadan ders politikama uysun"),
   dict(obj_en="retry policy", obj_tr="tekrar politikası",
        surface_en="Quiz settings", surface_tr="Sınav ayarları"), points=8),
 F("progress-dashboard", "report", "Analytics", ["analytics", "instructor"],
   ("instructor with 300 students", "300 öğrencisi olan eğitmen"),
   ("see which lessons students drop out of and which quiz questions they fail",
    "öğrencilerin hangi derslerde bıraktığını ve hangi sınav sorularında başarısız olduklarını görmek"),
   ("I can fix the weakest part of my course instead of guessing",
    "tahmin yürütmek yerine dersimin en zayıf kismini düzeltebileyim"),
   dict(obj_en="progress dashboard", obj_tr="ilerleme panosu",
        surface_en="Instructor analytics", surface_tr="Eğitmen analıtığı"), points=13),
 F("certificate-verify", "integration", "Certificates", ["certificates", "trust"],
   ("graduate applying for a job", "iş başvurusu yapan mezun"),
   ("share a certificate with a public verification link",
    "sertifikamı herkese açık doğrulama linkiyle paylaşmak"),
   ("an employer can confirm it is genuine without contacting us",
    "işveren bizimle iletişime geçmeden gerçekliğini doğrulayabilsin"),
   dict(obj_en="verifiable certificate", obj_tr="doğrulanabilir sertifika",
        surface_en="Certificates page", surface_tr="Sertifikalarım"), points=8),
 F("resume-playback", "realtime", "Course Player", ["player", "ux"],
   ("student switching devices", "cihaz değiştiren öğrenci"),
   ("resume a video at the exact second I stopped, on any device",
    "videoyu hangi cihazda olursam olayım bıraktığım saniyeden devam ettirmek"),
   ("I do not lose my place when I move from laptop to phone",
    "dizüstünden telefona geçince kaldığım yeri kaybetmeyeyim"),
   dict(obj_en="playback position sync", obj_tr="izleme konumu senkronu",
        surface_en="Course player", surface_tr="Ders oynatıcısı"), points=5),
 F("cohort-enrollment", "permission", "Enrollment", ["b2b", "enrollment"],
   ("corporate training manager", "kurumsal eğitim yöneticisi"),
   ("enrol a group of employees into a course with a single CSV",
    "bir grup çalışanı tek CSV ile bir derse kaydetmek"),
   ("I can onboard a new department without 60 manual invitations",
    "60 tane elle davet göndermeden yeni bir departmanı başlatabileyim"),
   dict(obj_en="cohort enrollment", obj_tr="toplu kayıt",
        surface_en="Organisation admin", surface_tr="Kurum yönetimi"), points=8),
], bugs=[
 B("video-progress-lost", "Course Player", ["player", "data"],
   ("watch progress resets to zero when the tab is closed quickly",
    "sekme hızlıca kapatıldığında izleme ilerlemesi sıfırlanıyor"),
   ("watching 20 minutes of a lesson and closing the tab within 10 seconds of pausing",
    "bir dersin 20 dakikasını izleyip duraklattıktan 10 saniye sonra sekmeyi kapatırken"),
   ("progress is persisted at least every 15 seconds",
    "ilerleme en az 15 saniyede bir kalıcı olarak kaydedilmeli"),
   ("the lesson shows 0% watched on the next visit",
    "ders bir sonraki girişe %0 izlendi görünüyor"),
   "progress flushed only on 'ended' and 60s interval; no visibilitychange/beacon", "Major", "frontend"),
 B("quiz-timer-refresh", "Assessments", ["assessment", "integrity"],
   ("refreshing the page grants a fresh quiz timer",
    "sayfayı yenilemek sınav süresini baştan başlatıyor"),
   ("pressing F5 during a timed quiz",
    "süreli bir sınav sırasında F5'e basıldığında"),
   ("the remaining time is computed from the server-side start timestamp",
    "kalan süre sunucu tarafındakı başlangıç zamanından hesaplanmalı"),
   ("the student gets the full duration again, unlimited times",
    "öğrenci sınırsız kez tam süreyi yeniden alıyor"),
   "timer initialised client-side from page load; attempt.started_at never checked", "Critical", "backend"),
 B("cert-name-encoding", "Certificates", ["pdf", "i18n"],
   ("Turkish characters in student names break the certificate PDF",
    "öğrenci adındakı Türkçe karakterler sertifika PDF'ini bozuyor"),
   ("generating a certificate for a student named with 'g', 's' or 'i' characters",
    "adında Türkçe karakter bulunan bir öğrenci için sertifika oluştururken"),
   ("the name is rendered exactly as stored",
    "ad kayıtlı olduğu gibi gösterilmeli"),
   ("the name renders as black boxes and support has to issue it manually",
    "ad siyah kutucuklar olarak çıkıyor ve destek sertifikayı elle düzenlemek zorunda kalıyor"),
   "PDF font subset lacks Latin Extended-A glyphs", "Major", "backend"),
 B("download-storage", "Mobile App", ["offline", "mobile"],
   ("offline downloads keep files after the course is unenrolled",
    "çevrimdışı indirmeler ders kaydı silindikten sonra da dosyaları tutuyor"),
   ("unenrolling from a course that has 4 GB of downloaded lessons",
    "4 GB indirilmiş dersi olan bir dersten kaydı silerken"),
   ("downloaded files for that course are deleted and storage is freed",
    "o derse ait indirilen dosyalar silinmeli ve alan boşaltılmalı"),
   ("the files stay on the device and cannot be deleted from the app",
    "dosyalar cihazda kalıyor ve uygulamadan silinemiyor"),
   "unenroll clears DB rows but not the AVAssetDownload cache directory", "Minor", "mobile"),
], epics=[
 E("course-completion", "Course Player", ["retention", "learning"],
   ("raise the share of enrolled students who finish a course",
    "derse kayıtlı olup dersi bitiren öğrenci oranını artırmak"),
   ("only 12% of enrolled students complete a course; 60% of drop-offs happen in the first three lessons",
    "kayıtlı öğrencilerin yalnızca %12'si dersi bitiriyor, bırakmaların %60'i ilk üç derste oluyor"),
   ("course completion rate", "ders tamamlama oranı"),
   "12%", "25%", "Q4",
   (["Add streak and weekly goal tracking with reminders",
     "Resume playback across devices at the exact position",
     "Add short knowledge checks after every third lesson",
     "Send a re-engagement email when a student is idle for 5 days"],
    ["Hatırlatmalı seri ve haftalık hedef takibi ekleme",
     "Cihazlar arası tam konumdan izlemeye devam özelliği",
     "Her üç derste bir kısa bilgi kontrolü ekleme",
     "5 gün hareketsiz öğrenciye geri kazanım e-postası gönderme"])),
])
