from .core import B, E, F, domain, register

# ---------------------------------------------------------------- PLATFORM / DEVOPS
d = domain("platform", "internal developer platform", "şirket içi geliştirici platformu", "PLAT",
           ["CI/CD", "Observability", "Kubernetes", "Data Pipeline", "Security",
            "Developer Portal", "Cost"])
register(d, features=[
 F("preview-envs", "integration", "CI/CD", ["ci", "developer-experience"],
   ("backend developer", "backend geliştirici"),
   ("get an isolated preview environment automatically for every pull request",
    "her pull request için otomatik olarak izole bir önizleme ortamı almak"),
   ("reviewers can click a link instead of pulling my branch locally",
    "inceleyenler dalımı yerelde çekmek yerine bir linke tıklayabilsin"),
   dict(obj_en="preview environment", obj_tr="önizleme ortamı",
        surface_en="Pull request checks", surface_tr="Pull request kontrolleri"), points=13),
 F("slo-dashboards", "report", "Observability", ["slo", "reliability"],
   ("service owner", "servis sahibi"),
   ("see a per-service SLO dashboard with error budget burn rate",
    "servis başına hata bütçesi tüketim hızını gösteren SLO panosu görmek"),
   ("I can tell whether to ship features or spend the sprint on reliability",
    "bu sprint özellik mi çıkaracağımı yoksa güvenilirliğe mi çalışacağımı bilebileyim"),
   dict(obj_en="SLO dashboard", obj_tr="SLO panosu",
        surface_en="Observability portal", surface_tr="Gözlemlenebilirlik portalı"), points=8),
 F("secret-rotation", "settings", "Security", ["secrets", "security"],
   ("platform engineer", "platform mühendisi"),
   ("rotate database credentials automatically without a deployment",
    "veritabanı kimlik bilgilerini dağıtım yapmadan otomatik rotasyona almak"),
   ("a leaked credential stops being useful within an hour",
    "sızan bir kimlik bilgisi bir saat içinde ise yaramaz hale gelsin"),
   dict(obj_en="automatic secret rotation", obj_tr="otomatik gizli anahtar rotasyonu",
        surface_en="Secrets manager", surface_tr="Gizli anahtar yöneticisi"), points=13),
 F("cost-per-service", "report", "Cost", ["finops", "cost"],
   ("engineering manager", "mühendislik yöneticisi"),
   ("see monthly cloud spend broken down by service and team",
    "aylık bulut harcamasını servis ve takım bazında döküm halinde görmek"),
   ("teams can see and own the cost of what they run",
    "takımlar çalıştırdıklarının maliyetini görüp sahiplenebilsin"),
   dict(obj_en="cost breakdown", obj_tr="maliyet dökümü",
        surface_en="Developer portal > Cost", surface_tr="Geliştirici portalı > Maliyet"), points=8),
 F("golden-path-template", "form", "Developer Portal", ["scaffolding", "dx"],
   ("developer starting a new service", "yeni bir servis başlatan geliştirici"),
   ("scaffold a new service with CI, logging, metrics and alerts already wired",
    "CI, loglama, metrik ve alarmları hazır bağlı yeni bir servis iskeleti oluşturmak"),
   ("a new service is production-ready on day one instead of week three",
    "yeni bir servis üçüncü hafta yerine ilk gün üretime hazır olsun"),
   dict(obj_en="service template", obj_tr="servis şablonu",
        surface_en="Developer portal", surface_tr="Geliştirici portalı"), points=13),
], bugs=[
 B("ci-flaky-cache", "CI/CD", ["ci", "flaky"],
   ("CI fails intermittently with a corrupted dependency cache",
    "CI zaman zaman bozuk bağımlılık önbelleği hatasıyla başarısız oluyor"),
   ("running the pipeline on a branch shortly after a lockfile change",
    "lock dosyası değiştikten kısa süre sonra dalda pipeline çalıştırırken"),
   ("the cache key changes with the lockfile and the build is reproducible",
    "önbellek anahtarı lock dosyasıyla değişmeli ve derleme tekrarlanabilir olmalı"),
   ("about 1 in 6 builds fails and passes on a blind re-run",
    "yaklaşık 6 derlemeden 1'i başarısız oluyor ve körlemesine yeniden çalıştırınca geçiyor"),
   "cache key hashes package.json only, not the lockfile", "Major", "infra"),
 B("alert-noise", "Observability", ["alerting", "reliability"],
   ("the on-call rotation receives 60+ non-actionable alerts per night",
    "nöbetçi ekip gecede 60'tan fazla aksiyon alınamayacak alarm alıyor"),
   ("a single pod restart during a routine deployment",
    "rutin bir dağıtım sırasında tek bir pod yeniden başlatıldığında"),
   ("one grouped alert fires only if the error budget is actually burning",
    "yalnızca hata bütçesi gerçekten tükeniyorsa tek bir gruplanmış alarm tetiklenmeli"),
   ("each replica fires its own page and on-call sleeps through real incidents",
    "her replika kendi çağrısını gönderiyor ve nöbetçi gerçek olayları uykuda kaçırıyor"),
   "alert rule has no for: duration and no grouping labels", "Major", "infra"),
 B("k8s-oomkill", "Kubernetes", ["kubernetes", "memory"],
   ("the report worker is OOMKilled during month-end processing",
    "rapor işleyicisi ay sonu işlemleri sırasında OOMKilled oluyor"),
   ("generating reports for tenants with more than 500k rows",
    "500 binden fazla satırı olan müşteriler için rapor oluştururken"),
   ("the worker streams rows and stays within its memory limit",
    "işleyici satırları akış halinde işlemeli ve bellek limitinde kalmalı"),
   ("the pod is killed at 2 GiB and the job restarts from the beginning",
    "pod 2 GiB'da sonlandırılıyor ve iş baştan başlıyor"),
   "reason=OOMKilled exit_code=137; full result set loaded with fetchall()", "Major", "backend"),
 B("pipeline-secret-log", "Security", ["secrets", "security"],
   ("a deploy token is printed in plain text in build logs",
    "dağıtım token'i derleme loglarında düz metin olarak yazdırılıyor"),
   ("running the deploy job with debug logging enabled",
    "hata ayıklama loglaması açıkkan dağıtım işi çalıştırıldığında"),
   ("the value is masked in every log sink",
    "değer tüm log hedeflerinde maskelenmeli"),
   ("the token appears unmasked and is retained for 90 days",
    "token maskelenmeden görünüyor ve 90 gün saklanıyor"),
   "secret injected via inline env echo; masking only covers vars declared as 'secret'", "Critical", "infra"),
], epics=[
 E("deploy-frequency", "CI/CD", ["dora", "developer-experience"],
   ("make shipping to production a daily, low-drama event",
    "üretime çıkmayı günlük ve gerilimsiz bir olay haline getirmek"),
   ("median lead time from merge to production is 4,5 days and change failure rate is 22%",
    "merge'den üretime medyan süre 4,5 gün ve değişiklik başarısızlık oranı %22"),
   ("lead time from merge to production", "merge'den üretime geçen süre"),
   "4,5 days", "under 1 day", "H1",
   (["Add automatic preview environments per pull request",
     "Split the 48-minute test suite into parallel shards under 10 minutes",
     "Add progressive delivery with automated rollback on SLO burn",
     "Replace manual release checklist with an automated release gate"],
    ["Pull request başına otomatik önizleme ortamı ekleme",
     "48 dakikalık test paketini 10 dakika altında paralel parçalara bölme",
     "SLO tüketiminde otomatik geri alan aşamalı dağıtım ekleme",
     "Elle yapılan sürüm kontrol listesini otomatik sürüm kapısıyla değiştirme"])),
])

# ---------------------------------------------------------------- GAMING
d = domain("gaming", "free-to-play mobile game", "ücretsiz mobil oyun", "GAME",
           ["Gameplay", "Live Ops", "Monetisation", "Player Account",
            "Matchmaking", "Client", "Backend"])
register(d, features=[
 F("battle-pass", "payment", "Monetisation", ["liveops", "monetisation"],
   ("returning player", "geri dönen oyuncu"),
   ("track battle pass progress and claim rewards from the main screen",
    "savaş bileti ilerlememi takip edip ödülleri ana ekrandan almak"),
   ("I always know what I am playing towards this season",
    "bu sezon ne için oynadığımı her zaman bileyim"),
   dict(obj_en="battle pass track", obj_tr="savaş bileti ilerlemesi",
        surface_en="Home screen", surface_tr="Ana ekran"), points=13),
 F("account-link", "auth", "Player Account", ["account", "retention"],
   ("player changing phones", "telefon değiştiren oyuncu"),
   ("link my progress to Apple or Google sign-in",
    "ilerlememi Apple veya Google girişiyle bağlamak"),
   ("I do not lose 200 hours of progress when I switch devices",
    "cihaz değiştirdiğimde 200 saatlik ilerlememi kaybetmeyeyim"),
   dict(obj_en="account linking", obj_tr="hesap bağlama",
        surface_en="Settings > Account", surface_tr="Ayarlar > Hesap"), points=8),
 F("skill-matchmaking", "realtime", "Matchmaking", ["matchmaking", "fairness"],
   ("competitive player", "rekabetçi oyuncu"),
   ("be matched against players within a similar skill band",
    "benzer beceri aralığındakı oyuncularla eşleştirilmek"),
   ("matches feel winnable instead of hopeless",
    "maçlar umutsuz değil kazanılabilir hissettirsin"),
   dict(obj_en="skill-based matchmaking", obj_tr="beceri bazlı eşleştirme",
        surface_en="Match queue", surface_tr="Maç kuyruğu"), points=13),
 F("offer-personalise", "report", "Monetisation", ["liveops", "personalisation"],
   ("live ops manager", "live ops yöneticisi"),
   ("target starter offers by player segment and playtime",
    "başlangıç paketlerini oyuncu segmentine ve oyun süresine göre hedeflemek"),
   ("offers feel relevant instead of spamming everyone the same bundle",
    "teklifler herkese aynı paketi spamlamak yerine ilgili hissettirsin"),
   dict(obj_en="targeted offer", obj_tr="hedefli teklif",
        surface_en="Live ops console", surface_tr="Live ops konsolu"), points=8),
], bugs=[
 B("purchase-not-granted", "Monetisation", ["iap", "revenue"],
   ("an in-app purchase is charged but the currency is not granted",
    "uygulama içi satın alma tahsil ediliyor ama oyun parası verilmiyor"),
   ("completing a purchase while the app loses connectivity mid-transaction",
    "işlem ortasında bağlantı kopan bir satın alma tamamlanırken"),
   ("the receipt is validated on reconnect and the currency is granted once",
    "makbuz yeniden bağlanıldığında doğrulanmalı ve para bir kez verilmeli"),
   ("the player is charged, receives nothing, and opens a support ticket",
    "oyuncudan para çekiliyor, hiçbir şey almıyor ve destek talebi açıyor"),
   "receipt validated client-side only; no pending-purchase replay on launch", "Critical", "backend"),
 B("battle-pass-rollover", "Live Ops", ["liveops", "timezone"],
   ("season rewards reset an hour early for players in some regions",
    "sezon ödülleri bazı bölgelerdeki oyuncular için bir saat erken sıfırlanıyor"),
   ("playing during the season rollover window in UTC+3",
    "UTC+3'te sezon geçiş saatinde oynarken"),
   ("the season ends at the same absolute moment for every player",
    "sezon her oyuncu için aynı mutlak anda bitmeli"),
   ("some players lose the last hour of progress before the deadline",
    "bazı oyuncular son bir saatlik ilerlemesini kaybediyor"),
   "season end computed from device local time instead of server UTC", "Major", "client"),
 B("matchmaking-wait", "Matchmaking", ["matchmaking", "performance"],
   ("queue times exceed four minutes for high-rank players at night",
    "gece saatlerinde yüksek dereceli oyuncular için kuyruk süresi dört dakikayı aşıyor"),
   ("queuing for ranked play after 01:00 local time",
    "yerel saatle 01:00'dan sonra dereceli maç kuyruğuna girerken"),
   ("the skill band widens gradually so a match is found within 90 seconds",
    "beceri aralığı kademeli genişleyip 90 saniye içinde maç bulunmalı"),
   ("the band never widens and 30% of players abandon the queue",
    "aralık hiç genişlemiyor ve oyuncuların %30'u kuyruğu terk ediyor"),
   "MMR window expansion step configured as 0 for tiers above Diamond", "Major", "backend"),
], epics=[
 E("d7-retention", "Gameplay", ["retention", "liveops"],
   ("improve day-7 retention for new players",
    "yeni oyuncuların 7. gün kalıcılık oranını artırmak"),
   ("day-7 retention is 9,4% versus a 15% genre benchmark; most churn happens right after the tutorial",
    "7. gün kalıcılık %9,4, tür ortalaması ise %15, kaybın çoğu eğitim bölümünün hemen ardından yaşanıyor"),
   ("day-7 retention", "7. gün kalıcılık oranı"),
   "9,4%", "15%", "Q3",
   (["Shorten the tutorial from 11 to 5 minutes with skippable steps",
     "Add a daily login reward chain for the first 7 days",
     "Add skill-based matchmaking for the first 20 matches",
     "Add push re-engagement for players idle for 48 hours"],
    ["Eğitim bölümünü atlanabilir adımlarla 11 dakikadan 5 dakikaya indirme",
     "İlk 7 gün için günlük giriş ödül zinciri ekleme",
     "İlk 20 maç için beceri bazlı eşleştirme ekleme",
     "48 saat hareketsiz oyunculara push ile geri kazanım ekleme"])),
])

# ---------------------------------------------------------------- MEDIA
d = domain("media", "video streaming service", "video yayın servisi", "STR",
           ["Playback", "Catalog", "Recommendations", "Subscriptions",
            "TV App", "Downloads", "Search"])
register(d, features=[
 F("continue-watching", "list", "Playback", ["ux", "playback"],
   ("subscriber watching a series", "dizi izleyen abone"),
   ("see a continue-watching row that keeps the correct next episode",
    "doğru sonraki bölümü tutan bir 'izlemeye devam et' satırı görmek"),
   ("I can resume without hunting through seasons",
    "sezonlar arasında aramadan devam edebileyim"),
   dict(obj_en="continue watching row", obj_tr="izlemeye devam et satırı",
        surface_en="Home screen", surface_tr="Ana ekran"), points=8),
 F("profile-kids", "permission", "Subscriptions", ["profiles", "safety"],
   ("parent sharing an account", "hesabını paylaşan ebeveyn"),
   ("create a kids profile with an age rating limit and a PIN to exit it",
    "yaş sınırı olan ve çıkışı PIN korumalı bir çocuk profili oluşturmak"),
   ("my child cannot open content meant for adults",
    "çocuğum yetişkinlere yönelik içeriği açamasın"),
   dict(obj_en="kids profile", obj_tr="çocuk profili",
        surface_en="Profile switcher", surface_tr="Profil seçici"), points=8),
 F("download-expiry", "notify", "Downloads", ["downloads", "licensing"],
   ("subscriber travelling", "seyahat eden abone"),
   ("see when a downloaded title expires and renew it before a flight",
    "indirilen bir içeriğin ne zaman geçerliliğini yitireceğini görüp uçuş öncesi yenilemek"),
   ("I am not stuck with an unplayable download on the plane",
    "uçakta oynatılamayan bir indirmeyle kalmayayım"),
   dict(obj_en="download expiry badge", obj_tr="indirme geçerlilik rozeti",
        surface_en="Downloads screen", surface_tr="İndirilenler ekranı"), points=5),
 F("skip-intro", "realtime", "Playback", ["playback", "ux"],
   ("binge watcher", "arka arkaya izleyen kullanıcı"),
   ("skip the intro with one click and have it auto-skip if I always do",
    "jeneriği tek tıkla atlamak ve hep atlıyorsam otomatik atlanması"),
   ("I lose fewer minutes across a full season",
    "bir sezon boyunca daha az dakika kaybedeyim"),
   dict(obj_en="skip intro control", obj_tr="jeneriği atla düğmesi",
        surface_en="Player overlay", surface_tr="Oynatıcı katmanı"), points=5),
], bugs=[
 B("hdr-washed", "Playback", ["playback", "tv"],
   ("HDR content looks washed out on certain 2021 TV models",
    "HDR içerik bazı 2021 model televizyonlarda soluk görünüyor"),
   ("playing an HDR10 title on an affected TV after an SDR trailer",
    "SDR bir fragmandan sonra etkilenen bir TV'de HDR10 içerik oynatılırken"),
   ("the player switches the display into HDR mode before the first frame",
    "oynatıcı ilk kareden önce ekranı HDR moduna geçirmeli"),
   ("the title plays in SDR tone mapping and colours are flat",
    "içerik SDR ton eşlemesiyle oynuyor ve renkler düz görünüyor"),
   "display mode switch requested after decoder init; race with surface creation", "Major", "client"),
 B("continue-wrong-ep", "Playback", ["playback", "data"],
   ("continue watching offers an episode the user already finished",
    "'izlemeye devam et' kullanıcının zaten bitirdiği bölümü öneriyor"),
   ("finishing an episode on TV and opening the mobile app within a minute",
    "TV'de bir bölümü bitirip bir dakika içinde mobil uygulamayı açarken"),
   ("the row shows the next unwatched episode on every device",
    "satır tüm cihazlarda bir sonraki izlenmemiş bölümü göstermeli"),
   ("mobile shows the finished episode at 97% for up to an hour",
    "mobil, biten bölümü bir saate kadar %97'de gösteriyor"),
   "progress events written to the read model asynchronously with 60m cache TTL", "Minor", "backend"),
 B("subtitle-offset", "Playback", ["subtitles", "accessibility"],
   ("subtitles drift out of sync by several seconds on long titles",
    "uzun içeriklerde altyazılar birkaç saniye kayıyor"),
   ("watching a title longer than 100 minutes past the halfway point",
    "100 dakikadan uzun bir içeriği yarısından sonra izlerken"),
   ("subtitle timing stays aligned for the full duration",
    "altyazı zamanlaması içerik boyunca hizalı kalmalı"),
   ("subtitles run 4-6 seconds ahead by the end",
    "altyazılar sona doğru 4-6 saniye öne geçiyor"),
   "WebVTT cue times assume constant frame rate; source is VFR 23,976/29,97", "Major", "client"),
], epics=[
 E("playback-startup", "Playback", ["performance", "cx"],
   ("cut the time between pressing play and the first frame",
    "oynat tuşuna başmakla ilk karenin gelmesi arasındakı süreyi kısaltmak"),
   ("median startup time is 4,1 seconds on TV apps and 8% of sessions are abandoned before the first frame",
    "TV uygulamalarında medyan başlama süresi 4,1 saniye ve oturumların %8'i ilk kare gelmeden terk ediliyor"),
   ("median playback startup time", "medyan oynatma başlama süresi"),
   "4,1 s", "under 1,5 s", "Q4",
   (["Prefetch the manifest and first segment on hover or focus",
     "Move DRM licence acquisition off the critical path",
     "Start playback at a lower bitrate and ramp up",
     "Add a startup-time dashboard broken down by device model"],
    ["Üzerine gelindiğinde manifest ve ilk segmenti önceden getirme",
     "DRM lisans alımını kritik yoldan çıkarma",
     "Oynatmayı düşük bit hızıyla başlatıp kademeli yükseltme",
     "Cihaz modeline göre ayrıştırılmış başlama süresi panosu ekleme"])),
])
