# -*- coding: utf-8 -*-
"""Lisansli spor bahisleri ve casino platformu.

Bu alan veri setine uc temayi getirir: saglayici (provider) entegrasyonu,
gercek zamanli oran/gecikme kisitlari ve mevzuat/sorumlu oyun yukumlulukleri.
"""
from .core import domain, register, F, B, E

d = domain("betting", "licensed sports betting and casino platform",
           "lisanslı spor bahisleri ve casino platformu", "BET",
           ["Sportsbook", "Live Betting", "Bet Slip", "Providers", "Payments",
            "Responsible Gaming", "KYC", "Bonus Engine", "Casino Integration",
            "Odds Feed"])

register(d, features=[
 F("cashout", "payment", "Bet Slip", ["cashout", "sportsbook"],
   ("bettor with an open coupon", "açık kuponu olan bahisçi"),
   ("cash out my open coupon at the offered amount before the match ends",
    "maç bitmeden açık kuponumu teklif edilen tutardan nakde çevirmek"),
   ("I can take a certain return instead of risking the whole stake",
    "tüm tutarı riske atmak yerine kesin bir getiriyi alabileyim"),
   dict(obj_en="cash-out offer", obj_tr="nakde çevirme teklifi",
        surface_en="Open coupons", surface_tr="Açık kuponlarım"), points=13),
 F("bet-builder", "form", "Sportsbook", ["betslip", "sportsbook"],
   ("bettor following one match", "tek maçı takip eden bahisçi"),
   ("combine several markets from the same match into one coupon",
    "aynı maçtan birden fazla bahis seçeneğini tek kuponda birleştirmek"),
   ("I can back my full read of the match in a single bet",
    "maça dair bütün öngörümü tek bahiste oynayabileyim"),
   dict(obj_en="bet builder", obj_tr="kupon oluşturucu",
        surface_en="Match detail", surface_tr="Maç detayı"), points=13),
 F("live-odds-stream", "realtime", "Odds Feed", ["live", "odds"],
   ("live bettor", "canlı bahis oynayan kullanıcı"),
   ("see odds update the moment they change, without refreshing",
    "oranların değiştiği anda yenileme yapmadan güncellendiğini görmek"),
   ("I do not place a bet on an odds value that is already gone",
    "çoktan geçmiş bir oran üzerinden bahis oynamayayım"),
   dict(obj_en="live odds stream", obj_tr="canlı oran akışı",
        surface_en="Live betting board", surface_tr="Canlı bahis panosu"), points=13),
 F("deposit-limit", "settings", "Responsible Gaming", ["compliance", "responsible-gaming"],
   ("player managing their spending", "harcamasını yönetmek isteyen oyuncu"),
   ("set a daily, weekly and monthly deposit limit on my account",
    "hesabıma günlük, haftalık ve aylık para yatırma limiti koymak"),
   ("I stay within the budget I decided on when I was calm",
    "sakin kafayla belirlediğim bütçenin içinde kalabileyim"),
   dict(obj_en="deposit limit", obj_tr="para yatırma limiti",
        surface_en="Responsible gaming settings", surface_tr="Sorumlu oyun ayarları"), points=8),
 F("self-exclusion", "permission", "Responsible Gaming", ["compliance", "responsible-gaming"],
   ("player who wants to stop", "ara vermek isteyen oyuncu"),
   ("exclude myself from the platform for a period I choose",
    "seçtiğim bir süre boyunca kendimi platformdan hariç tutmak"),
   ("the decision holds even when I change my mind at 2am",
    "gece iki'de fikrim değişse bile kararım geçerli kalsın"),
   dict(obj_en="self-exclusion", obj_tr="kendini hariç tutma",
        surface_en="Account settings", surface_tr="Hesap ayarları"), points=8),
 F("provider-aggregator", "integration", "Providers", ["providers", "integration"],
   ("platform integration engineer", "platform entegrasyon mühendisi"),
   ("onboard a new game provider through one aggregation layer instead of a bespoke integration",
    "yeni bir oyun sağlayıcısını özel entegrasyon yerine tek bir toplama katmanı üzerinden eklemek"),
   ("a new provider goes live in days instead of a full quarter",
    "yeni bir sağlayıcı bir çeyrek yerine günler içinde yayına girsin"),
   dict(obj_en="provider aggregation layer", obj_tr="sağlayıcı toplama katmanı",
        surface_en="Provider console", surface_tr="Sağlayıcı konsolu"), points=13),
 F("bet-history-export", "export", "Sportsbook", ["export", "transparency"],
   ("player reviewing their season", "sezonunu gözden geçiren oyuncu"),
   ("download my full bet history for a date range as CSV",
    "seçtiğim tarih aralığındaki tüm bahis geçmişimi CSV olarak indirmek"),
   ("I can see what I actually staked and returned over the season",
    "sezon boyunca gerçekte ne yatırdığımı ve ne kazandığımı görebileyim"),
   dict(obj_en="bet history export", obj_tr="bahis geçmişi dışa aktarımı",
        surface_en="My bets", surface_tr="Bahislerim"), points=5),
 F("age-verification", "upload", "KYC", ["compliance", "kyc"],
   ("new registrant", "yeni kayıt olan kullanıcı"),
   ("verify my age and identity before my first deposit",
    "ilk para yatırma işlemimden önce yaşımı ve kimliğimi doğrulamak"),
   ("I can use the platform legally without a manual review queue",
    "elle inceleme kuyruğunda beklemeden platformu yasal biçimde kullanabileyim"),
   dict(obj_en="age and identity check", obj_tr="yaş ve kimlik doğrulaması",
        surface_en="Registration step 3", surface_tr="Kayıt 3. adım"), points=13),
 F("bonus-wagering", "report", "Bonus Engine", ["bonus", "transparency"],
   ("player holding a bonus", "bonusu olan oyuncu"),
   ("see exactly how much wagering is left before my bonus converts to cash",
    "bonusumun nakde dönmesi için ne kadar çevrim kaldığını net olarak görmek"),
   ("I understand the rules instead of guessing why my bonus is locked",
    "bonusumun neden kilitli olduğunu tahmin etmek yerine kuralları anlayabileyim"),
   dict(obj_en="wagering progress", obj_tr="çevrim ilerlemesi",
        surface_en="Bonuses page", surface_tr="Bonuslarım"), points=8),
 F("odds-change-consent", "form", "Bet Slip", ["betslip", "ux"],
   ("bettor placing a coupon", "kupon oynayan bahisçi"),
   ("choose whether my coupon is accepted automatically when odds move up",
    "oranlar yükseldiğinde kuponumun otomatik kabul edilip edilmeyeceğini seçmek"),
   ("my coupon is not rejected over a tiny odds change I would have accepted",
    "kabul edeceğim küçücük bir oran değişimi yüzünden kuponum reddedilmesin"),
   dict(obj_en="odds change preference", obj_tr="oran değişimi tercihi",
        surface_en="Bet slip settings", surface_tr="Kupon ayarları"), points=5),
], bugs=[
 B("stale-odds-accept", "Odds Feed", ["odds", "race-condition"],
   ("coupons are accepted at odds that changed seconds earlier",
    "kuponlar saniyeler önce değişmiş oranlardan kabul ediliyor"),
   ("placing a live bet within two seconds of an odds update",
    "oran güncellemesinden iki saniye içinde canlı bahis oynarken"),
   ("the coupon is rejected or re-offered at the current odds",
    "kupon reddedilmeli ya da güncel oranla yeniden teklif edilmeli"),
   ("the bet is settled at the old odds and the risk position is wrong",
    "bahis eski orandan sonuçlanıyor ve risk pozisyonu hatalı oluyor"),
   "odds snapshot read from cache with 4s TTL; no version check at acceptance", "Critical", "backend"),
 B("cashout-mismatch", "Bet Slip", ["cashout", "money"],
   ("the cash-out amount shown differs from the amount actually credited",
    "gösterilen nakde çevirme tutarı ile hesaba geçen tutar farklı oluyor"),
   ("accepting a cash-out offer while the match score changes",
    "maç skoru değişirken nakde çevirme teklifini kabul ederken"),
   ("the accepted offer is honoured or clearly re-quoted before confirmation",
    "kabul edilen teklif ya uygulanmalı ya da onaydan önce açıkça yeniden fiyatlanmalı"),
   ("the player is credited a lower amount with no explanation",
    "oyuncunun hesabına açıklama olmadan daha düşük bir tutar geçiyor"),
   "cash-out price recalculated after user confirmation without re-confirmation step", "Critical", "backend"),
 B("provider-timeout-hang", "Providers", ["providers", "reliability"],
   ("a casino game freezes when the provider does not respond",
    "sağlayıcı yanıt vermediğinde casino oyunu donuyor"),
   ("opening a game from the affected provider during their maintenance window",
    "etkilenen sağlayıcının bakım penceresinde oyununu açarken"),
   ("a timeout is detected within 10 seconds and the player is returned to the lobby with the stake untouched",
    "10 saniye içinde zaman aşımı algılanmalı ve oyuncu bahsi el değmeden lobiye döndürülmeli"),
   ("the loading screen stays forever and the stake shows as reserved for an hour",
    "yükleme ekranı sonsuza kadar kalıyor ve bahis bir saat boyunca rezerve görünüyor"),
   "no client-side timeout on provider launch call; stake reservation TTL is 3600s", "Major", "integration"),
 B("limit-bypass", "Responsible Gaming", ["compliance", "responsible-gaming"],
   ("the daily deposit limit can be exceeded with two simultaneous deposits",
    "günlük para yatırma limiti aynı anda yapılan iki işlemle aşılabiliyor"),
   ("starting two deposits in separate tabs within the same second",
    "aynı saniye içinde iki ayrı sekmede para yatırma başlatıldığında"),
   ("the second deposit is rejected once the limit is reached",
    "limit dolduğunda ikinci para yatırma reddedilmeli"),
   ("both deposits succeed and the account is over the limit the player set",
    "iki işlem de başarılı oluyor ve hesap oyuncunun koyduğu limiti aşıyor"),
   "limit check is read-then-write without a row lock on the player's limit counter", "Critical", "backend"),
 B("settlement-delay", "Sportsbook", ["settlement", "data"],
   ("coupons stay open for hours after the match has finished",
    "maç bittikten saatler sonra kuponlar açık kalmaya devam ediyor"),
   ("waiting for settlement on a match that ended with a VAR-corrected score",
    "VAR ile düzeltilmiş skorla biten bir maçın sonuçlanmasını beklerken"),
   ("coupons settle within 5 minutes of the official result, or the delay is explained in the app",
    "kuponlar resmî sonuçtan sonra 5 dakika içinde sonuçlanmalı ya da gecikme uygulamada açıklanmalı"),
   ("coupons sit in 'open' with no message and support gets a wave of tickets",
    "kuponlar mesajsız biçimde 'açık' kalıyor ve desteğe talep yağıyor"),
   "result feed sends a correction event the settlement worker treats as a duplicate and drops", "Major", "data"),
 B("balance-drift", "Payments", ["money", "data"],
   ("the displayed balance and the ledger balance differ after a failed withdrawal",
    "başarısız para çekme sonrası görünen bakiye ile defterdeki bakiye farklı oluyor"),
   ("a withdrawal that is rejected by the payment provider after being reserved",
    "rezerve edildikten sonra ödeme sağlayıcısı tarafından reddedilen bir çekim işleminde"),
   ("the reserved amount is released and both balances match",
    "rezerve tutar serbest bırakılmalı ve iki bakiye de eşleşmeli"),
   ("the amount stays reserved and the player sees less money than they have",
    "tutar rezerve kalıyor ve oyuncu sahip olduğundan az para görüyor"),
   "compensating transaction not emitted on provider callback status=REJECTED", "Critical", "backend"),
 B("bonus-double-credit", "Bonus Engine", ["bonus", "duplicate"],
   ("a welcome bonus is credited twice when registration is retried",
    "kayıt işlemi tekrar denendiğinde hoş geldin bonusu iki kez yükleniyor"),
   ("completing registration after the first attempt times out at the KYC step",
    "ilk deneme KYC adımında zaman aşımına uğradıktan sonra kaydı tamamlarken"),
   ("the bonus is granted exactly once per player",
    "bonus oyuncu başına tam olarak bir kez verilmeli"),
   ("some accounts receive the bonus twice and finance reverses it manually days later",
    "bazı hesaplara bonus iki kez geçiyor ve finans günler sonra elle geri alıyor"),
   "bonus grant keyed on registration_attempt_id instead of player_id", "Major", "backend"),
 B("live-stream-desync", "Live Betting", ["live", "mobile"],
   ("the live stream runs 12 seconds behind the odds board",
    "canlı yayın oran panosunun 12 saniye gerisinden gidiyor"),
   ("watching the stream and the live betting board on the same screen",
    "yayını ve canlı bahis panosunu aynı ekranda izlerken"),
   ("the delay between the stream and the odds is stated in the interface",
    "yayın ile oranlar arasındaki gecikme arayüzde belirtilmeli"),
   ("the player sees a goal on the board before the stream and assumes the odds are broken",
    "oyuncu golü yayından önce panoda görüyor ve oranların bozuk olduğunu sanıyor"),
   "no delay indicator; stream buffer 12s vs odds websocket ~300ms", "Minor", "frontend"),
], epics=[
 E("responsible-gaming-programme", "Responsible Gaming", ["compliance", "responsible-gaming"],
   ("give players effective tools to control their play before harm occurs",
    "oyunculara zarar oluşmadan önce oyunlarını kontrol edebilecekleri etkili araçlar sunmak"),
   ("only 4% of active players have set any limit, and the regulator's next audit expects documented intervention flows",
    "aktif oyuncuların yalnızca %4'ü herhangi bir limit tanımlamış ve düzenleyicinin bir sonraki denetimi belgelenmiş müdahale akışları bekliyor"),
   ("share of active players with at least one self-set limit",
    "en az bir limit tanımlamış aktif oyuncu oranı"),
   "4%", "25%", "Q4",
   (["Add daily, weekly and monthly deposit limits with a cooling-off period on increases",
     "Add reality-check reminders after a configurable session length",
     "Add self-exclusion for 1 day to 6 months with no early reversal",
     "Detect risky patterns and surface a support message in-product",
     "Publish a player-facing activity summary with staked, returned and net figures"],
    ["Artışlarda bekleme süresi olan günlük, haftalık ve aylık yatırım limitleri ekleme",
     "Yapılandırılabilir oturum süresinden sonra gerçeklik kontrolü hatırlatması ekleme",
     "1 gün ile 6 ay arası, erken geri alınamayan kendini hariç tutma ekleme",
     "Riskli oyun desenlerini tespit edip ürün içinde destek mesajı gösterme",
     "Yatırılan, kazanılan ve net tutarı gösteren oyuncuya açık aktivite özeti yayınlama"])),
 E("provider-onboarding", "Providers", ["providers", "integration"],
   ("cut the time it takes to bring a new game provider live",
    "yeni bir oyun sağlayıcısını yayına almak için geçen süreyi kısaltmak"),
   ("each provider currently takes 9-14 weeks of bespoke integration work and three of them share 80% of the same API surface",
    "her sağlayıcı şu anda 9-14 haftalık özel entegrasyon işi gerektiriyor ve üçü API yüzeyinin %80'ini paylaşıyor"),
   ("weeks from provider contract to live traffic",
    "sağlayıcı sözleşmesinden canlı trafiğe geçen hafta sayısı"),
   "11 weeks", "3 weeks", "H1",
   (["Define one internal game-launch and wallet contract for all providers",
     "Build an adapter layer with a conformance test suite each provider must pass",
     "Add a provider sandbox where integrations run against recorded traffic",
     "Add per-provider circuit breakers and timeout budgets",
     "Migrate the two highest-volume providers onto the new layer"],
    ["Tüm sağlayıcılar için tek bir oyun başlatma ve cüzdan sözleşmesi tanımlama",
     "Her sağlayıcının geçmesi gereken uyumluluk test paketiyle adaptör katmanı kurma",
     "Entegrasyonların kayıtlı trafiğe karşı çalıştığı bir sağlayıcı sandbox'ı ekleme",
     "Sağlayıcı bazında devre kesici ve zaman aşımı bütçeleri ekleme",
     "En yüksek hacimli iki sağlayıcıyı yeni katmana taşıma"])),
 E("live-latency", "Live Betting", ["performance", "live"],
   ("make live betting feel instant and fair during peak matches",
    "yoğun maçlarda canlı bahsi anlık ve adil hissettirmek"),
   ("during derby matches the odds board lags up to 4 seconds and 11% of live coupons are rejected for odds changes",
    "derbi maçlarında oran panosu 4 saniyeye kadar geride kalıyor ve canlı kuponların %11'i oran değişimi yüzünden reddediliyor"),
   ("live coupon rejection rate caused by odds change",
    "oran değişimi nedeniyle reddedilen canlı kupon oranı"),
   "11%", "4%", "Q3",
   (["Push odds over a websocket instead of 3-second polling",
     "Add an odds version token that the coupon carries to acceptance",
     "Let players opt in to accepting improved odds automatically",
     "Show the stream delay next to the live board so the gap is explained",
     "Load test the odds path at derby-level concurrency before the season"],
    ["Oranları 3 saniyelik yoklama yerine websocket üzerinden gönderme",
     "Kuponun kabul aşamasına taşıdığı bir oran sürüm anahtarı ekleme",
     "Oyunculara iyileşen oranları otomatik kabul etme seçeneği sunma",
     "Yayın gecikmesini canlı panonun yanında göstererek farkı açıklama",
     "Sezon öncesi oran akışını derbi seviyesinde eşzamanlılıkla yük testine tabi tutma"])),
])
