# -*- coding: utf-8 -*-
"""Task ve Spike cekirdekleri.

Bunlar domain'den bagimsizdir: her domain'in kendi bilesen/servis adlariyla
doldurulur. Task = sonucu yalnizca ekibin gordugu is. Spike = ciktisi karar
olan, sure kutulu arastirma.
"""
from dataclasses import dataclass, field


@dataclass
class Task:
    slug: str
    area: str                 # backend | infra | data | frontend | mobile | qa
    labels: list
    points: int
    obj_en: str; obj_tr: str
    ctx_en: str; ctx_tr: str
    steps_en: list; steps_tr: list
    done_en: list; done_tr: list
    domain: str = ""
    component: str = ""


@dataclass
class Spike:
    slug: str
    area: str
    labels: list
    timebox_en: str; timebox_tr: str
    q_en: list; q_tr: list
    scope_en: list; scope_tr: list
    deliver_en: str; deliver_tr: str
    crit_en: list; crit_tr: list
    domain: str = ""
    component: str = ""


def T(slug, area, labels, points, obj, ctx, steps, done):
    return Task(slug, area, labels, points, obj[0], obj[1], ctx[0], ctx[1],
                steps[0], steps[1], done[0], done[1])


def S(slug, area, labels, timebox, q, scope, deliver, crit):
    return Spike(slug, area, labels, timebox[0], timebox[1], q[0], q[1],
                 scope[0], scope[1], deliver[0], deliver[1], crit[0], crit[1])


TASKS = [
 T("runtime-upgrade", "infra", ["tech-debt", "upgrade"], 5,
   ("Upgrade {svc} to the current LTS runtime",
    "{svc} servisini güncel LTS çalışma zamanına yükselt"),
   ("The version we run leaves security support in {quarter}; nothing changes for users but we cannot take patches after that date.",
    "Kullandığımız sürümün güvenlik desteği {quarter} içinde bitiyor; kullanıcı için bir şey değişmiyor ama o tarihten sonra yama alamıyoruz."),
   (["Bump the base image and lockfile, resolve breaking changes",
     "Run the full test suite and fix deprecation warnings",
     "Deploy to staging and soak for 48 hours",
     "Roll out to production one region at a time"],
    ["Temel imajı ve lock dosyasını yükselt, kırıcı değişiklikleri çöz",
     "Tüm test paketini çalıştır, kullanımdan kalkma uyarılarını gider",
     "Staging'e dağıt ve 48 saat gözlem altında tut",
     "Üretime bölge bölge çık"]),
   (["Service runs on the LTS version in production",
     "No new error classes in the 48 hours after rollout",
     "p95 latency within 5% of the previous version"],
    ["Servis üretimde LTS sürümünde çalışıyor",
     "Yayından sonraki 48 saatte yeni hata sınıfı yok",
     "p95 gecikme önceki sürümün %5 bandında"])),
 T("dead-flag-cleanup", "backend", ["tech-debt", "cleanup"], 2,
   ("Remove the {flag} feature flag and its dead branches",
    "{flag} feature flag'ini ve ölü dallarını kaldır"),
   ("The flag has been at 100% for six months. The dormant branch still ships in every build and confuses new joiners.",
    "Bayrak altı aydır %100'de. Kullanılmayan dal hâlâ her derlemeye giriyor ve yeni katılanların kafasını karıştırıyor."),
   (["Confirm the flag is at 100% in every environment",
     "Delete the branch that is no longer reachable",
     "Remove the flag definition from the config service",
     "Delete the tests that only covered the old branch"],
    ["Bayrağın tüm ortamlarda %100'de olduğunu doğrula",
     "Artık erişilemeyen dalı sil",
     "Bayrak tanımını config servisinden kaldır",
     "Yalnızca eski dalı kapsayan testleri sil"]),
   (["No reference to the flag remains in the codebase",
     "Test suite still green, coverage did not drop"],
    ["Kod tabanında bayrağa ait referans kalmadı",
     "Test paketi hâlâ yeşil, kapsam düşmedi"])),
 T("db-index", "data", ["performance", "database"], 3,
   ("Add a covering index for the {component} list query",
    "{component} liste sorgusu için kapsayıcı indeks ekle"),
   ("The list query does a sequential scan and takes 2,4 s at p95 on the largest tenant. Users see it as a slow page, but the fix is purely internal.",
    "Liste sorgusu sıralı tarama yapıyor ve en büyük müşteride p95'te 2,4 saniye sürüyor. Kullanıcı bunu yavaş sayfa olarak görüyor ama çözüm tamamen iç tarafta."),
   (["Capture the slow query plan from production",
     "Create the index concurrently on a replica first",
     "Measure before/after on a production-sized dataset",
     "Apply in production during the low-traffic window"],
    ["Üretimden yavaş sorgu planını al",
     "İndeksi önce bir replika üzerinde eşzamanlı oluştur",
     "Üretim boyutundaki veri setinde önce/sonra ölç",
     "Üretimde düşük trafik penceresinde uygula"]),
   (["p95 for the query is under 200 ms on the largest tenant",
     "Write throughput did not regress by more than 3%",
     "Migration is reversible and documented"],
    ["En büyük müşteride sorgu p95'i 200 ms altında",
     "Yazma verimi %3'ten fazla gerilemedi",
     "Migration geri alınabilir ve dokümante edilmiş"])),
 T("test-suite-split", "qa", ["ci", "developer-experience"], 5,
   ("Split the test suite into parallel shards under 10 minutes",
    "Test paketini 10 dakikanın altında paralel parçalara böl"),
   ("The suite takes 48 minutes, so people stop waiting for CI and merge on a hunch. No product behaviour changes here.",
    "Paket 48 dakika sürüyor, bu yüzden kimse CI'ı beklemiyor ve tahminle merge ediyor. Burada ürün davranışı değişmiyor."),
   (["Measure per-file runtime and find the slow tail",
     "Split into four shards balanced by measured duration",
     "Move the three slowest integration tests to a nightly job",
     "Publish a merged coverage report from the shards"],
    ["Dosya başına süreyi ölç ve yavaş kuyruğu bul",
     "Ölçülen süreye göre dengelenmiş dört parçaya böl",
     "En yavaş üç entegrasyon testini gecelik işe taşı",
     "Parçalardan birleştirilmiş kapsam raporu yayınla"]),
   (["Wall-clock CI time is under 10 minutes on the default branch",
     "Coverage report is identical to the single-shard run"],
    ["Varsayılan dalda CI süresi 10 dakikanın altında",
     "Kapsam raporu tek parçalı çalıştırmayla aynı"])),
 T("log-pii-scrub", "backend", ["security", "compliance"], 3,
   ("Mask personal data in {svc} logs before they leave the service",
    "{svc} loglarındaki kişisel veriyi servis dışına çıkmadan maskele"),
   ("An audit found e-mail addresses and phone numbers in plain text in the log pipeline, retained for 90 days.",
    "Bir denetimde log hattında düz metin e-posta adresleri ve telefon numaraları bulundu; bunlar 90 gün saklanıyor."),
   (["Add a scrubbing layer to the logger with a field allow-list",
     "Add unit tests that assert masked output for known fields",
     "Backfill: purge the affected indices older than the retention rule",
     "Add a CI check that fails on new unmasked field names"],
    ["Logger'a alan izin listeli bir maskeleme katmanı ekle",
     "Bilinen alanlar için maskeli çıktıyı doğrulayan birim testleri ekle",
     "Geriye dönük: saklama kuralını aşan etkilenmiş indeksleri temizle",
     "Yeni maskelenmemiş alan adlarında hata veren bir CI kontrolü ekle"]),
   (["No personal field appears unmasked in any log sink",
     "CI blocks a pull request that logs a new personal field"],
    ["Hiçbir log hedefinde maskelenmemiş kişisel alan görünmüyor",
     "Yeni bir kişisel alan loglayan pull request CI tarafından engelleniyor"])),
 T("idempotency-keys", "backend", ["reliability", "backend"], 8,
   ("Add idempotency keys to the {svc} write endpoints",
    "{svc} yazma uç noktalarına idempotency anahtarı ekle"),
   ("Client retries create duplicate records. Support cleans them up by hand, roughly 40 cases a week.",
    "İstemci yeniden denemeleri mükerrer kayıt oluşturuyor. Destek bunları elle temizliyor, haftada yaklaşık 40 vaka."),
   (["Accept and persist an Idempotency-Key header with a 24 hour window",
     "Return the original response for a repeated key",
     "Add a store with TTL and a uniqueness constraint",
     "Document the header in the public API reference"],
    ["24 saatlik pencereyle Idempotency-Key başlığını kabul et ve sakla",
     "Tekrarlanan anahtar için ilk yanıtı geri dön",
     "TTL ve tekillik kısıtı olan bir depo ekle",
     "Başlığı genel API referansında dokümante et"]),
   (["The same key twice creates exactly one record",
     "Load test with 5% duplicate traffic produces no duplicates",
     "API reference documents the header and the window"],
    ["Aynı anahtar iki kez gönderildiğinde tam olarak tek kayıt oluşuyor",
     "%5 mükerrer trafikli yük testinde mükerrer kayıt oluşmuyor",
     "API referansı başlığı ve pencereyi dokümante ediyor"])),
 T("alert-tuning", "infra", ["observability", "reliability"], 3,
   ("Cut non-actionable alerts in the {component} on-call rotation",
    "{component} nöbet rotasyonundaki aksiyon alınamayan alarmları azalt"),
   ("On-call receives 60+ pages a night and has started muting the channel, which is how the last real incident was missed for 40 minutes.",
    "Nöbetçi gecede 60'tan fazla çağrı alıyor ve kanalı sessize almaya başladı; son gerçek olayın 40 dakika fark edilmemesinin sebebi bu."),
   (["Classify last month's alerts as actionable or noise",
     "Add a `for:` duration and grouping labels to the noisy rules",
     "Convert three threshold alerts into error-budget burn alerts",
     "Route non-urgent alerts to a ticket queue instead of paging"],
    ["Geçen ayın alarmlarını aksiyon alınabilir/gürültü olarak sınıflandır",
     "Gürültülü kurallara `for:` süresi ve gruplama etiketleri ekle",
     "Üç eşik alarmını hata bütçesi tüketim alarmına çevir",
     "Acil olmayan alarmları çağrı yerine bir talep kuyruğuna yönlendir"]),
   (["Nightly page count is below 5 for a full week",
     "Every remaining alert has a linked runbook"],
    ["Bir hafta boyunca gecelik çağrı sayısı 5'in altında",
     "Kalan her alarmın bağlı bir runbook'u var"])),
 T("data-retention", "data", ["compliance", "data"], 5,
   ("Implement the retention policy for {component} records",
    "{component} kayıtları için saklama politikasını uygula"),
   ("Legal set a 24 month retention limit; today records are kept indefinitely and the table grows 40 GB a quarter.",
    "Hukuk 24 aylık saklama sınırı belirledi; bugün kayıtlar süresiz tutuluyor ve tablo çeyrek başına 40 GB büyüyor."),
   (["Add a deleted_at column and a scheduled purge job",
     "Anonymise instead of deleting where a foreign key requires the row",
     "Add an audit record for each purge run",
     "Dry-run against a production copy and review the counts"],
    ["deleted_at kolonu ve zamanlanmış temizleme işi ekle",
     "Yabancı anahtar satırı zorunlu kılıyorsa silmek yerine anonimleştir",
     "Her temizleme çalışması için denetim kaydı ekle",
     "Üretim kopyasında kuru çalıştırma yap ve sayıları incele"]),
   (["No record older than 24 months remains outside the legal-hold set",
     "Purge job reports counts and runs within its window"],
    ["Yasal saklama seti dışında 24 aydan eski kayıt kalmadı",
     "Temizleme işi sayıları raporluyor ve penceresi içinde tamamlanıyor"])),
 T("api-pagination", "backend", ["api", "performance"], 5,
   ("Replace offset pagination with cursor pagination in the {svc} API",
    "{svc} API'sinde offset sayfalamayı imleç sayfalamayla değiştir"),
   ("Deep pages time out for large tenants and results shift when records are inserted mid-scan. Public API, so it needs a deprecation path.",
    "Büyük müşterilerde derin sayfalar zaman aşımına uğruyor ve tarama sırasında kayıt eklendiğinde sonuçlar kayıyor. Genel API olduğu için kullanımdan kaldırma yolu gerekiyor."),
   (["Add cursor parameters alongside the existing offset ones",
     "Mark offset parameters deprecated in the OpenAPI spec",
     "Notify integrators with a 90 day migration window",
     "Remove offset support after the window closes"],
    ["Mevcut offset parametrelerinin yanına imleç parametrelerini ekle",
     "OpenAPI tanımında offset parametrelerini kullanımdan kalkmış olarak işaretle",
     "Entegratörleri 90 günlük geçiş penceresiyle bilgilendir",
     "Pencere kapandıktan sonra offset desteğini kaldır"]),
   (["Page 500 responds in under 300 ms on the largest tenant",
     "Results are stable when rows are inserted during iteration",
     "Deprecation notice is live in the API reference"],
    ["En büyük müşteride 500. sayfa 300 ms altında yanıt veriyor",
     "Yineleme sırasında satır eklendiğinde sonuçlar kaymıyor",
     "Kullanımdan kaldırma duyurusu API referansında yayında"])),
 T("i18n-extract", "frontend", ["i18n", "frontend"], 3,
   ("Extract hard-coded strings in {component} into locale files",
    "{component} içindeki koda gömülü metinleri dil dosyalarına taşı"),
   ("Turkish copy changes currently require a frontend deploy. 140 strings are hard-coded across the module.",
    "Türkçe metin değişiklikleri şu anda frontend dağıtımı gerektiriyor. Modül genelinde 140 metin koda gömülü."),
   (["Extract the strings into the locale bundle with stable keys",
     "Add a lint rule that fails on new literal user-facing strings",
     "Have the TR copy reviewed by the content owner",
     "Verify layout with the longest translation"],
    ["Metinleri sabit anahtarlarla dil paketine çıkar",
     "Kullanıcıya görünen yeni düz metinde hata veren lint kuralı ekle",
     "TR metinlerini içerik sahibine incelet",
     "En uzun çeviriyle düzeni doğrula"]),
   (["No user-facing literal string remains in the module",
     "Lint blocks a pull request that adds one",
     "Layout holds with the longest translation"],
    ["Modülde kullanıcıya görünen düz metin kalmadı",
     "Yeni metin ekleyen pull request lint tarafından engelleniyor",
     "En uzun çeviriyle düzen bozulmuyor"])),
 T("secret-rotation-run", "infra", ["security", "secrets"], 2,
   ("Rotate the {svc} database credentials",
    "{svc} veritabanı kimlik bilgilerini rotasyona al"),
   ("The credentials are 14 months old and were shared in a chat thread during an incident. No user-facing change.",
    "Kimlik bilgileri 14 aylık ve bir olay sırasında sohbet başlığında paylaşılmıştı. Kullanıcıya yansıyan bir değişiklik yok."),
   (["Create the new credential in the secret manager",
     "Deploy with dual credentials accepted",
     "Switch traffic and confirm zero auth errors",
     "Revoke the old credential and purge it from chat history"],
    ["Gizli anahtar yöneticisinde yeni kimlik bilgisini oluştur",
     "İki kimlik bilgisini de kabul eden sürümü dağıt",
     "Trafiği geçir ve sıfır yetkilendirme hatası olduğunu doğrula",
     "Eski kimlik bilgisini iptal et ve sohbet geçmişinden temizle"]),
   (["Old credential is revoked and rejected by the database",
     "No authentication errors during or after the switch"],
    ["Eski kimlik bilgisi iptal edilmiş ve veritabanı tarafından reddediliyor",
     "Geçiş sırasında ve sonrasında yetkilendirme hatası yok"])),
 T("dependency-audit", "backend", ["security", "tech-debt"], 3,
   ("Resolve the high-severity findings in the {svc} dependency audit",
    "{svc} bağımlılık taramasındaki yüksek önemli bulguları gider"),
   ("The scanner reports 7 high findings, 3 of them reachable from request handling code.",
    "Tarayıcı 7 yüksek bulgu raporluyor, bunların 3'ü istek işleme kodundan erişilebilir durumda."),
   (["Triage each finding for actual reachability",
     "Upgrade the reachable ones and run the regression suite",
     "Document an accepted risk for the unreachable ones with an expiry date",
     "Wire the scanner into CI as a blocking check"],
    ["Her bulguyu gerçekten erişilebilir mi diye triyaj et",
     "Erişilebilir olanları yükselt ve regresyon paketini çalıştır",
     "Erişilemez olanlar için son kullanma tarihli kabul edilmiş risk kaydı yaz",
     "Tarayıcıyı CI'a engelleyici kontrol olarak bağla"]),
   (["No reachable high-severity finding remains",
     "CI fails on a newly introduced high finding"],
    ["Erişilebilir yüksek önemli bulgu kalmadı",
     "Yeni eklenen yüksek bulguda CI hata veriyor"])),
 T("mobile-crash-fix-infra", "mobile", ["mobile", "observability"], 3,
   ("Add symbolicated crash reporting to the {component} mobile build",
    "{component} mobil derlemesine sembolleştirilmiş çökme raporlaması ekle"),
   ("Crash reports arrive without symbols, so the top three crashes have been unactionable for two releases.",
    "Çökme raporları sembolsüz geliyor; bu yüzden en sık üç çökme iki sürümdür üzerine gidilemiyor."),
   (["Upload dSYM and mapping files from the release pipeline",
     "Verify symbolication on a deliberately crashed build",
     "Set an alert on the crash-free session rate"],
    ["Sürüm hattından dSYM ve mapping dosyalarını yükle",
     "Bilerek çökertilen bir derlemede sembolleştirmeyi doğrula",
     "Çökmesiz oturum oranına alarm kur"]),
   (["New crashes appear with readable stack frames",
     "Crash-free session rate is visible on the release dashboard"],
    ["Yeni çökmeler okunabilir yığın çerçeveleriyle görünüyor",
     "Çökmesiz oturum oranı sürüm panosunda görünür"])),
]

SPIKES = [
 S("queue-vs-stream", "backend", ["architecture", "spike"],
   ("3 days, one engineer", "3 gün, bir mühendis"),
   (["Can the existing queue deliver the ordering guarantee we need?",
     "What is the operational cost difference over 12 months?",
     "What is the migration path if we start on the queue and outgrow it?"],
    ["Mevcut kuyruk ihtiyacımız olan sıralama garantisini verebilir mi?",
     "12 aylık operasyon maliyeti farkı ne?",
     "Kuyrukla başlayıp yetersiz kalırsa geçiş yolu ne olur?"]),
   (["Prototype both options with a realistic message volume",
     "Measure ordering, replay and back-pressure behaviour",
     "Price both at the projected volume"],
    ["İki seçeneği de gerçekçi mesaj hacmiyle prototiple",
     "Sıralama, yeniden oynatma ve geri basınç davranışını ölç",
     "Öngörülen hacimde ikisini de fiyatla"]),
   ("A one-page comparison with a recommendation and an ADR draft",
    "Öneri içeren tek sayfalık karşılaştırma ve bir ADR taslağı"),
   (["Ordering guarantee is the hard requirement; cost is the tiebreaker",
     "Team can operate the choice without a new on-call skill set"],
    ["Sıralama garantisi zorunlu koşul; maliyet eşitlik bozucu",
     "Ekip seçimi yeni bir nöbet uzmanlığı gerektirmeden işletebilmeli"])),
 S("vendor-compare", "backend", ["vendor", "spike"],
   ("5 days, two engineers", "5 gün, iki mühendis"),
   (["Do both vendors meet our latency and uptime requirements?",
     "What does the data processing agreement allow?",
     "What is the exit cost if we switch away in 18 months?"],
    ["İki tedarikçi de gecikme ve çalışma süresi gereksinimlerimizi karşılıyor mu?",
     "Veri işleme sözleşmesi neye izin veriyor?",
     "18 ay sonra çıkarsak ayrılma maliyeti ne olur?"]),
   (["Run the same integration test suite against both sandboxes",
     "Have legal review both data processing agreements",
     "Model the cost at current and 3x volume"],
    ["Aynı entegrasyon test paketini iki sandbox üzerinde çalıştır",
     "İki veri işleme sözleşmesini de hukuka incelet",
     "Mevcut ve 3 katı hacimde maliyeti modelle"]),
   ("A comparison table, the test results and a signed-off recommendation",
    "Karşılaştırma tablosu, test sonuçları ve onaylanmış bir öneri"),
   (["Latency p95 under 300 ms at our volume",
     "No data leaves the EU region",
     "Exit is possible without re-implementing the integration"],
    ["Bizim hacmimizde p95 gecikme 300 ms altında",
     "Hiçbir veri AB bölgesi dışına çıkmıyor",
     "Entegrasyonu baştan yazmadan çıkış mümkün"])),
 S("load-capacity", "infra", ["performance", "spike"],
   ("2 days, one engineer", "2 gün, bir mühendis"),
   (["What is the current breaking point of {svc}?",
     "Which resource saturates first: CPU, connections or the database?",
     "How much headroom does the launch traffic estimate leave?"],
    ["{svc} servisinin mevcut kırılma noktası ne?",
     "Önce hangi kaynak doluyor: CPU, bağlantı sayısı yoksa veritabanı?",
     "Lansman trafiği tahmini ne kadar pay bırakıyor?"]),
   (["Run a stepped load test against a production-shaped environment",
     "Record saturation points and error onset for each resource",
     "Test the autoscaling reaction time"],
    ["Üretim benzeri ortamda kademeli yük testi çalıştır",
     "Her kaynak için doyum noktasını ve hataların başladığı anı kaydet",
     "Otomatik ölçekleme tepki süresini test et"]),
   ("A capacity note with the breaking point, the first bottleneck and a scaling recommendation",
    "Kırılma noktasını, ilk darboğazı ve ölçekleme önerisini içeren kapasite notu"),
   (["Breaking point is at least 3x the launch estimate, or we scale before launch",
     "The first bottleneck has a known mitigation"],
    ["Kırılma noktası lansman tahmininin en az 3 katı, değilse lansman öncesi ölçeklenir",
     "İlk darboğazın bilinen bir çözümü var"])),
 S("regulation-scope", "backend", ["compliance", "spike"],
   ("3 days, one engineer with legal", "3 gün, bir mühendis ve hukuk"),
   (["Does the regulation apply to the data we hold in {component}?",
     "Which obligations would be new for us?",
     "What is the deadline and the penalty for missing it?"],
    ["Düzenleme {component} bileşeninde tuttuğumuz veriyi kapsıyor mu?",
     "Hangi yükümlülükler bizim için yeni olur?",
     "Son tarih ne ve kaçırmanın yaptırımı ne?"]),
   (["Map our data categories against the regulation's definitions",
     "Review with legal and write down the disagreements",
     "List the gaps as candidate backlog items"],
    ["Veri kategorilerimizi düzenlemenin tanımlarıyla eşleştir",
     "Hukukla birlikte incele ve anlaşmazlıkları yaz",
     "Boşlukları aday backlog maddeleri olarak listele"]),
   ("A scope memo signed off by legal plus a gap list",
    "Hukuk tarafından onaylanmış kapsam notu ve bir boşluk listesi"),
   (["Legal agrees with the scope conclusion in writing",
     "Every gap has an owner and a rough size"],
    ["Hukuk kapsam sonucuna yazılı olarak katılıyor",
     "Her boşluğun bir sahibi ve kaba bir büyüklüğü var"])),
 S("ml-feasibility", "data", ["ml", "spike"],
   ("5 days, one data scientist", "5 gün, bir veri bilimci"),
   (["Is the historical data good enough to train a useful model?",
     "What baseline does a simple rule-based approach reach?",
     "What would inference cost per 1000 requests?"],
    ["Geçmiş veri işe yarar bir model eğitmeye yetecek kalitede mi?",
     "Basit kural tabanlı bir yaklaşım hangi temel seviyeye ulaşıyor?",
     "1000 istek başına çıkarım maliyeti ne olur?"]),
   (["Profile label quality and class balance on 12 months of data",
     "Train one baseline model and compare it to the rule-based approach",
     "Estimate serving cost at projected volume"],
    ["12 aylık veride etiket kalitesini ve sınıf dengesini profille",
     "Bir temel model eğit ve kural tabanlı yaklaşımla karşılaştır",
     "Öngörülen hacimde servis maliyetini tahmin et"]),
   ("A notebook with the baseline numbers and a go/no-go recommendation",
    "Temel sayıları içeren bir notebook ve devam/durdur önerisi"),
   (["The model must beat the rule-based baseline by a clear margin",
     "Label quality is sufficient without a new annotation effort"],
    ["Model kural tabanlı temel seviyeyi belirgin farkla geçmeli",
     "Etiket kalitesi yeni bir etiketleme çalışması gerektirmeyecek düzeyde"])),
 S("offline-sync-approach", "mobile", ["mobile", "architecture", "spike"],
   ("4 days, one mobile engineer", "4 gün, bir mobil mühendis"),
   (["Which conflict resolution strategy fits our edit patterns?",
     "How large can the local store grow on a mid-range device?",
     "Can we reuse the existing sync library or do we need our own?"],
    ["Düzenleme desenlerimize hangi çakışma çözme stratejisi uyuyor?",
     "Orta seviye bir cihazda yerel depo ne kadar büyüyebilir?",
     "Mevcut senkron kütüphanesini kullanabilir miyiz yoksa kendimizinkini mi yazmalıyız?"]),
   (["Prototype last-write-wins and per-field merge on real edit traces",
     "Measure storage growth over a simulated month of use",
     "Evaluate two candidate libraries against our schema"],
    ["Gerçek düzenleme izleri üzerinde son-yazan-kazanır ve alan bazlı birleştirmeyi prototiple",
     "Simüle edilmiş bir aylık kullanımda depolama büyümesini ölç",
     "İki aday kütüphaneyi şemamıza karşı değerlendir"]),
   ("A prototype branch plus a written recommendation on the conflict strategy",
    "Bir prototip dal ve çakışma stratejisi üzerine yazılı öneri"),
   (["No silent data loss in the chosen strategy",
     "Local store stays under 500 MB for a heavy month of use"],
    ["Seçilen stratejide sessiz veri kaybı yok",
     "Yoğun bir aylık kullanımda yerel depo 500 MB altında kalıyor"])),
]
