"""Pattern bazli Acceptance Criteria ureteci.

Her AC bir Given/When/Then uclusudur. Sablonlar {obj}, {surface}, {persona}
degiskenleriyle doldurulur. Her feature icin en az bir mutlu yol, bir hata yolu
ve bir sinir durumu secilir (bkz. research/JIRA_STANDARDS.md 3.3).
"""

# kategori: happy | error | edge | security | state | nfr | a11y
AC = {
"form": [
 ("happy", ("the {persona} is on {surface} with valid input",
            "they save the {obj}",
            "the {obj} is persisted and a success confirmation is shown"),
           ("{persona} {surface} üzerinde geçerli bilgilerle bulunuyorken",
            "{obj} kaydedildiğinde",
            "{obj} kalıcı olarak saklanır ve başarı onayı gösterilir")),
 ("error", ("a required field is left empty",
            "the user attempts to save",
            "an inline error is shown next to that field and nothing is saved"),
           ("zorunlu bir alan boş bırağılmışkan",
            "kullanıcı kaydetmeye çalıştığında",
            "ilgili alanın yanında satır içi hata gösterilir ve kayıt yapılmaz")),
 ("edge", ("the {obj} already exists with the same values",
           "the user saves again",
           "no duplicate is created and the existing record is updated"),
          ("aynı değerlerle bir {obj} zaten varken",
           "kullanıcı tekrar kaydettiğinde",
           "mükerrer kayıt oluşturulmaz, mevcut kayıt güncellenir")),
 ("state", ("the form has unsaved changes",
            "the user navigates away",
            "a confirmation dialog warns about losing changes"),
           ("formda kaydedilmemiş değişiklikler varken",
            "kullanıcı sayfadan ayrılmaya çalıştığında",
            "değişikliklerin kaybolacağını bildiren bir onay penceresi gösterilir")),
 ("nfr", ("the network request fails or times out",
          "the user saves",
          "the input is preserved and a retry action is offered"),
         ("ağ isteği başarısız olduğunda veya zaman aşımına uğradığında",
          "kullanıcı kaydettiğinde",
          "girilen bilgiler korunur ve yeniden deneme seçeneği sunulur")),
],
"list": [
 ("happy", ("the {persona} opens {surface}",
            "the list loads",
            "items are shown newest first with a visible total count"),
           ("{persona} {surface} sayfasını açtığında",
            "liste yüklendiğinde",
            "kayıtlar en yeniden eskiye sıralanır ve toplam sayı görünür")),
 ("edge", ("there are no items yet",
           "the list loads",
           "an empty state explains what the list is for and offers the primary action"),
          ("henüz hiç kayıt yokken",
           "liste yüklendiğinde",
           "listenin ne ise yaradığını anlatan ve ana aksiyonu sunan boş durum gösterilir")),
 ("edge", ("the list contains more than {items} items",
           "the user scrolls to the bottom",
           "the next page loads without losing scroll position"),
          ("listede {items}'den fazla kayıt varken",
           "kullanıcı en alta kaydırdığında",
           "kaydırma konumu kaybolmadan sonraki sayfa yüklenir")),
 ("state", ("the user has applied filters and reloads the page",
            "the page finishes loading",
            "the previously applied filters are still active"),
           ("kullanıcı filtre uygulayıp sayfayı yeniledikten sonra",
            "sayfa yüklendiğinde",
            "daha önce uygulanan filtreler hâlâ aktiftir")),
 ("error", ("the backend returns an error",
            "the list is requested",
            "an error state with a retry button is shown instead of an empty list"),
           ("sunucu hata dondurduğunda",
            "liste iştendiğinde",
            "boş liste yerine yeniden deneme düğmeli hata durumu gösterilir")),
],
"auth": [
 ("happy", ("a registered {persona} has {obj} enabled",
            "they authenticate on {surface}",
            "they are signed in within {sec3} seconds and land on the home screen"),
           ("kayıtlı bir {persona} için {obj} etkinleştirilmişken",
            "{surface} üzerinden doğrulama yaptığında",
            "{sec3} saniye içinde giriş yapar ve ana ekrana yönlendirilir")),
 ("error", ("authentication fails {ntry} times in a row",
            "the user tries again",
            "the account is temporarily locked and a recovery path is offered"),
           ("doğrulama ust üste {ntry} kez başarısız olduğunda",
            "kullanıcı tekrar denediğinde",
            "hesap geçici olarak kılıtlanır ve kurtarma yolu sunulur")),
 ("security", ("the session token has expired",
               "any authenticated request is made",
               "the request is rejected with 401 and the user is asked to sign in again"),
              ("oturum anahtarının süresi dolmuşken",
               "kimlik gerektiren herhangi bir istek yapıldığında",
               "istek 401 ile reddedilir ve kullanıcıdan tekrar giriş yapması istenir")),
 ("edge", ("{obj} is not available on the device",
           "the user opens {surface}",
           "the app falls back to password login without an error dialog"),
          ("cihazda {obj} kullanılamıyorken",
           "kullanıcı {surface} sayfasını açtığında",
           "uygulama hata penceresi göstermeden şifre ile girişe döner")),
 ("security", ("a user signs in on a new device",
               "authentication succeeds",
               "a security notification is sent to the registered email"),
              ("kullanıcı yeni bir cihazdan giriş yaptığında",
               "doğrulama başarılı olduğunda",
               "kayıtlı e-posta adresine güvenlik bildirimi gönderilir")),
],
"payment": [
 ("happy", ("the {persona} has a valid payment method",
            "they confirm the {obj}",
            "the transaction is authorised and a receipt with a reference number is shown"),
           ("{persona} geçerli bir ödeme yöntemine sahipken",
            "{obj} işlemini onayladığında",
            "işlem yetkilendirilir ve referans numaralı bir makbuz gösterilir")),
 ("error", ("the payment provider declines the transaction",
            "the user confirms",
            "the reason is shown in plain language and no amount is captured"),
           ("ödeme sağlayıcısı işlemi reddettiğinde",
            "kullanıcı onayladığında",
            "sebep sade bir dille gösterilir ve hiçbir tutar tahsil edilmez")),
 ("edge", ("the user taps confirm twice within one second",
           "both requests reach the server",
           "only one transaction is created (idempotency key enforced)"),
          ("kullanıcı onay tuşuna bir saniye içinde iki kez bastığında",
           "iki istek de sunucuya ulaştığında",
           "yalnızca tek bir işlem oluşturulur (idempotency anahtarı zorunludur)")),
 ("edge", ("the connection drops after the request is sent",
           "the app reopens",
           "the final state of the transaction is fetched and shown, not assumed"),
          ("istek gönderildikten sonra bağlantı koptuğunda",
           "uygulama yeniden açıldığında",
           "işlemin nihai durumu varsayılmaz, sunucudan çekilip gösterilir")),
 ("nfr", ("the transaction is authorised",
          "the response is returned",
          "an immutable audit record with actor, amount and timestamp is written"),
         ("işlem yetkilendirildiğinde",
          "yanıt döndüğünde",
          "aktör, tutar ve zaman damgası içeren değiştirilemez denetim kaydı yazılır")),
],
"search": [
 ("happy", ("the catalogue contains matching records",
            "the {persona} searches on {surface}",
            "the most relevant results are returned within {ms} ms"),
           ("eşleşen kayıtlar mevcutken",
            "{persona} {surface} üzerinde arama yaptığında",
            "en alakalı sonuçlar {ms} ms içinde döndürülür")),
 ("edge", ("the query contains Turkish characters or diacritics",
           "the search runs",
           "results match regardless of diacritics and letter casing"),
          ("sorgu Türkçe karakter veya aksan içerdiğinde",
           "arama çalıştırıldığında",
           "sonuçlar aksan ve büyük/küçük harften bağımsız eşleşir")),
 ("edge", ("no record matches the query",
           "the search runs",
           "a zero-result state with suggestions or a spelling correction is shown"),
          ("sorguyla eşleşen kayıt bulunmadığında",
           "arama çalıştırıldığında",
           "öneri veya yazım düzeltmesi içeren sıfır sonuç durumu gösterilir")),
 ("state", ("the user applies {obj} and reloads",
            "the page renders",
            "the selection is restored from the URL so the link is shareable"),
           ("kullanıcı {obj} uygulayıp sayfayı yeniledikten sonra",
            "sayfa oluştuğunda",
            "seçim URL'den geri yüklenir ve link paylaşılabilir olur")),
 ("nfr", ("a search returns zero results",
          "the request completes",
          "the query is logged for merchandising review without personal data"),
         ("bir arama sıfır sonuç döndürdüğünde",
          "istek tamamlandığında",
          "sorgu kişisel veri içermeden merchandising incelemesi için loglanır")),
],
"upload": [
 ("happy", ("the {persona} selects a supported file on {surface}",
            "the upload completes",
            "a preview is shown and the file is linked to the record"),
           ("{persona} {surface} üzerinde desteklenen bir dosya seçtiğinde",
            "yükleme tamamlandığında",
            "önizleme gösterilir ve dosya ilgili kayda bağlanır")),
 ("error", ("the file exceeds the size limit or has an unsupported format",
            "the user attempts to upload",
            "a specific error naming the limit and accepted formats is shown"),
           ("dosya boyut limitini aşıyorsa veya desteklenmeyen bir formattaysa",
            "kullanıcı yüklemeye çalıştığında",
            "limiti ve kabul edilen formatları belirten net bir hata gösterilir")),
 ("edge", ("the device is offline",
           "the user completes the step",
           "the file is queued locally and uploaded automatically when connectivity returns"),
          ("cihaz çevrimdışıyken",
           "kullanıcı adımı tamamladığında",
           "dosya yerelde kuyruğa alınır ve bağlantı gelince otomatik yüklenir")),
 ("security", ("an uploaded file contains executable content",
               "the upload is processed",
               "the file is rejected by content-type sniffing, not by extension alone"),
              ("yüklenen dosya çalıştırılabilir içerik barındırıyorsa",
               "yükleme işlendiğinde",
               "dosya yalnızca uzantıya göre değil içerik türü analiziyle reddedilir")),
 ("nfr", ("the upload is in progress",
          "the user watches {surface}",
          "a determinate progress indicator and a cancel action are available"),
         ("yükleme devam ederken",
          "kullanıcı {surface} sayfasını izlerken",
          "yüzde gösteren ilerleme çubuğu ve iptal seçeneği bulunur")),
],
"report": [
 ("happy", ("data exists for the selected period",
            "the {persona} opens {surface}",
            "the {obj} renders with the period, filters and last-refresh time visible"),
           ("seçilen dönem için veri mevcutken",
            "{persona} {surface} sayfasını açtığında",
            "{obj} dönem, filtreler ve son güncellenme zamanı görünür şekilde oluşur")),
 ("edge", ("the selected period has no data",
           "the report is generated",
           "an explicit 'no data for this period' state is shown instead of zeros"),
          ("seçilen dönemde veri yokken",
           "rapor oluşturulduğunda",
           "sıfırlar yerine açıkça 'bu dönemde veri yok' durumu gösterilir")),
 ("edge", ("the report covers more than {rows_big} rows",
           "the user requests it",
           "it is generated asynchronously and the user is notified when ready"),
          ("rapor {rows_big}'den fazla satır kapsıyorsa",
           "kullanıcı raporu talep ettiğinde",
           "rapor asenkron üretilir ve hazır olduğunda kullanıcıya bildirilir")),
 ("security", ("the {persona} lacks permission for a data segment",
               "the report is generated",
               "that segment is excluded rather than shown as zero"),
              ("{persona} bir veri segmenti için yetkiye sahip değilse",
               "rapor oluşturulduğunda",
               "o segment sıfır olarak değil, tamamen hariç tutularak gösterilir")),
 ("nfr", ("figures are shown to the user",
          "any total is displayed",
          "the same query run twice on unchanged data returns identical totals"),
         ("rakamlar kullanıcıya gösterildiğinde",
          "herhangi bir toplam görüntülendiğinde",
          "değişmeyen veri üzerinde aynı sorgu iki kez çalıştırıldığında aynı sonucu verir")),
],
"notify": [
 ("happy", ("the triggering event occurs and the {persona} has notifications enabled",
            "the event is processed",
            "exactly one {obj} is delivered within {sec30} seconds"),
           ("tetikleyici olay gerçekleştiğinde ve {persona} bildirimleri açmışkan",
            "olay işlendiğinde",
            "{sec30} saniye içinde tam olarak bir {obj} iletilir")),
 ("edge", ("the same event is republished by the message broker",
           "it is processed again",
           "no duplicate notification is sent (deduplicated by event id)"),
          ("aynı olay mesaj kuyruğu tarafından tekrar yayınlandığında",
           "olay yeniden işlendiğinde",
           "mükerrer bildirim gönderilmez (olay kimliğiyle tekilleştirilir)")),
 ("state", ("the user has turned this notification type off",
            "the event occurs",
            "no notification is sent and the suppression is recorded"),
           ("kullanıcı bu bildirim türünü kapatmışsa",
            "olay gerçekleştiğinde",
            "bildirim gönderilmez ve engelleme kaydedilir")),
 ("edge", ("the underlying record is cancelled before delivery",
           "the queued notification is due",
           "the queued notification is cancelled too"),
          ("ilgili kayıt iletimden önce iptal edildiğinde",
           "kuyruktakı bildirimin zamanı geldiğinde",
           "kuyruktakı bildirim de iptal edilir")),
 ("a11y", ("the notification is opened",
           "the app is launched from it",
           "the user lands on the relevant record, not the generic home screen"),
          ("bildirime dokunulduğunda",
           "uygulama bildirimden açıldığında",
           "kullanıcı genel ana ekrana değil ilgili kayda yönlendirilir")),
],
"integration": [
 ("happy", ("valid credentials are configured for {obj}",
            "the integration runs",
            "records sync in both directions and the last sync time is displayed"),
           ("{obj} için geçerli kimlik bilgileri tanımlıyken",
            "entegrasyon çalıştığında",
            "kayıtlar iki yönlü senkronize olur ve son senkron zamanı gösterilir")),
 ("error", ("the third-party service returns 5xx",
            "the call is made",
            "it is retried with exponential backoff and moved to a dead-letter queue after {hrs} hours"),
           ("üçüncü parti servis 5xx dondurduğunda",
            "çağrı yapıldığında",
            "üstel bekleme ile yeniden denenir ve {hrs} saat sonra olu mektup kuyruğuna alınır")),
 ("security", ("credentials are stored for the integration",
               "they are persisted",
               "they are encrypted at rest and never written to logs"),
              ("entegrasyon için kimlik bilgileri saklandığında",
               "veri kalıcı hale getirildiğinde",
               "bilgiler şifrelenerek saklanır ve loglara aşla yazılmaz")),
 ("edge", ("the same payload is delivered twice",
           "it is processed",
           "the result is identical to processing it once (idempotent)"),
          ("aynı veri iki kez iletildiğinde",
           "veri işlendiğinde",
           "sonuç tek kez işlenmiş gibidir (idempotent)")),
 ("nfr", ("the integration fails for a tenant",
          "the failure is detected",
          "an alert names the tenant, the error and the failing operation"),
         ("entegrasyon bir müşteri için başarısız olduğunda",
          "hata tespit edildiğinde",
          "alarm müşteriyi, hatayı ve başarısız işlemi açıkça belirtir")),
],
"settings": [
 ("happy", ("the {persona} changes {obj} on {surface}",
            "the change is saved",
            "it takes effect immediately without requiring a restart"),
           ("{persona} {surface} üzerindeyken",
            "{obj} ayarını değiştirip kaydettiğinde",
            "yeniden başlatma gerektirmeden anında etkili olur")),
 ("state", ("the setting has been changed",
            "the user signs in on another device",
            "the same value is applied there"),
           ("ayar değiştirildikten sonra",
            "kullanıcı başka bir cihazdan giriş yaptığında",
            "aynı değer orada da uygulanır")),
 ("security", ("the change affects security or money",
               "it is saved",
               "the user re-authenticates and the change is written to the audit log"),
              ("değişiklik güvenliği veya parayı etkiliyorsa",
               "kaydedildiğinde",
               "kullanıcıdan yeniden doğrulama istenir ve değişiklik denetim kaydına yazılır")),
 ("edge", ("the change fails on the server",
           "the response returns",
           "the UI reverts to the previous value instead of showing a false success"),
          ("değişiklik sunucuda başarısız olduğunda",
           "yanıt döndüğünde",
           "arayüz yanlış başarı göstermek yerine önceki değere geri döner")),
],
"realtime": [
 ("happy", ("the {persona} is on {surface}",
            "the underlying state changes on the server",
            "the view updates within {sec2} seconds without a manual refresh"),
           ("{persona} {surface} üzerindeyken",
            "sunucudakı durum değiştiğinde",
            "görünüm elle yenileme olmadan {sec2} saniye içinde güncellenir")),
 ("edge", ("the connection is lost",
           "connectivity returns",
           "the client reconnects automatically and back-fills missed updates"),
          ("bağlantı koptuğunda",
           "bağlantı geri geldiğinde",
           "istemci otomatik olarak yeniden bağlanır ve kaçırdığı güncellemeleri tamamlar")),
 ("edge", ("the device switches between Wi-Fi and mobile data",
           "the network change happens mid-session",
           "the session survives the switch or recovers within {sec5} seconds"),
          ("cihaz Wi-Fi ile mobil veri arasında geçiş yaptığında",
           "ağ değişimi oturum sırasında gerçekleştiğinde",
           "oturum geçişi atlatır veya {sec5} saniye içinde toparlanır")),
 ("nfr", ("{conc} concurrent viewers are connected",
          "an update is broadcast",
          "p95 delivery latency stays under {sec2} seconds"),
         ("{conc} eş zamanlı izleyici bağlıyken",
          "bir güncelleme yayınlandığında",
          "p95 iletim gecikmesi {sec2} saniyenin altında kalır")),
],
"permission": [
 ("happy", ("a {persona} is granted a role on a resource",
            "they open that resource",
            "they see exactly the actions their role allows"),
           ("bir {persona} kaynak üzerinde rol aldığında",
            "o kaynağı açtığında",
            "yalnızca rolünün izin verdiği aksiyonları görür")),
 ("security", ("a user without permission calls the API directly",
               "the request is made",
               "it is rejected with 403 and no data is leaked in the error body"),
              ("yetkisiz bir kullanıcı API'yi doğrudan çağırdığında",
               "istek yapıldığında",
               "istek 403 ile reddedilir ve hata gövdesinde veri sızmaz")),
 ("security", ("a role is revoked",
               "the user makes their next request",
               "the new permissions apply immediately without waiting for cache expiry"),
              ("bir rol geri alındığında",
               "kullanıcı bir sonraki isteğini yaptığında",
               "önbellek süresinin dolması beklenmeden yeni yetkiler uygulanır")),
 ("edge", ("a resource is shared with someone with narrower access",
           "they open the shared link",
           "results are re-filtered against their own permissions"),
          ("bir kaynak daha dar yetkili biriyle paylaşıldığında",
           "paylaşılan linği açtığında",
           "sonuçlar kendi yetkilerine göre yeniden filtrelenir")),
],
"export": [
 ("happy", ("the {persona} requests {obj} for a date range",
            "the export completes",
            "the file downloads with the period in its filename and matches the on-screen totals"),
           ("{persona} bir tarih aralığı için {obj} talep ettiğinde",
            "dışa aktarma tamamlandığında",
            "dosya adında dönem bilgisiyle iner ve ekrandakı toplamlarla birebir uyuşur")),
 ("edge", ("the export contains Turkish characters",
           "the file is opened in Excel",
           "characters render correctly (UTF-8 with BOM or an explicit encoding)"),
          ("dışa aktarım Türkçe karakter içerdiğinde",
           "dosya Excel'de açıldığında",
           "karakterler doğru görünür (BOM'lu UTF-8 veya açık kodlama)")),
 ("security", ("the export contains personal data",
               "it is generated",
               "the download link expires within {hrs} hours and the access is audit-logged"),
              ("dışa aktarım kişisel veri içerdiğinde",
               "dosya oluşturulduğunda",
               "indirme linği {hrs} saat içinde geçersiz olur ve erişim denetim kaydına yazılır")),
 ("edge", ("the export exceeds {rows} rows",
           "it is requested",
           "it is produced in the background and delivered by email or notification"),
          ("dışa aktarım {rows} satırı aştığında",
           "talep yapıldığında",
           "dosya arka planda üretilir ve e-posta ya da bildirimle iletilir")),
],
}


# Desenden bagimsiz, her ozellige uygulanabilen kriterler. AC havuzunun
# tekrara dusmesini engellemek icin desen sablonlariyla karistirilir.
CROSS = [
 ("state", ("the {persona} leaves {surface} in the middle of the flow",
            "they come back within the same session",
            "the entered data is still there and the flow resumes where it stopped"),
           ("{persona} akışın ortasında {surface} bölümünden ayrıldığında",
            "aynı oturum içinde geri döndüğünde",
            "girdiği veri duruyor ve akış kaldığı yerden devam eder")),
 ("error", ("the same request is submitted twice in quick succession",
            "both reach the server",
            "only the first is processed and the second returns the first result"),
           ("aynı istek arka arkaya iki kez gönderildiğinde",
            "ikisi de sunucuya ulaştığında",
            "yalnızca ilki işlenir ve ikincisi ilkinin sonucunu döndürür")),
 ("edge", ("the account has reached its plan limit for this resource",
           "the {persona} tries to create another one",
           "a clear message names the limit and offers the upgrade path"),
          ("hesap bu kaynak için plan limitine ulaşmışken",
           "{persona} bir tane daha oluşturmaya çalıştığında",
           "limiti adıyla belirten ve yükseltme yolunu sunan net bir mesaj gösterilir")),
 ("security", ("the {persona} belongs to a different tenant",
               "they request the record by its id",
               "the response is 404, not 403, so record existence is not leaked"),
              ("{persona} başka bir müşteriye ait olduğunda",
               "kaydı kimliğiyle istediğinde",
               "yanıt 403 değil 404 olur, böylece kaydın varlığı sızmaz")),
 ("edge", ("two people edit the same record at the same time",
           "the second one saves",
           "they are told the record changed and can see the difference before overwriting"),
          ("iki kişi aynı kaydı aynı anda düzenlediğinde",
           "ikincisi kaydettiğinde",
           "kaydın değiştiği bildirilir ve üzerine yazmadan önce farkı görebilir")),
 ("state", ("the operation succeeds",
            "the {persona} refreshes the page",
            "the result is still visible without re-running the operation"),
           ("işlem başarılı olduğunda",
            "{persona} sayfayı yenilediğinde",
            "sonuç, işlem tekrar çalıştırılmadan hâlâ görünür")),
 ("error", ("a downstream service is unavailable",
            "the {persona} performs the action",
            "the failure is explained in plain language and no partial state is left behind"),
           ("bağımlı bir servis erişilemez durumdayken",
            "{persona} işlemi yaptığında",
            "hata sade bir dille açıklanır ve yarım kalmış bir durum bırakılmaz")),
 ("nfr", ("the action changes data",
          "it completes",
          "an audit entry records who did it, when, and what changed"),
         ("işlem veriyi değiştirdiğinde",
          "tamamlandığında",
          "kimin, ne zaman, neyi değiştirdiğini gösteren bir denetim kaydı yazılır")),
 ("edge", ("the {persona} is on a slow connection",
           "the action takes longer than {sec3} seconds",
           "a progress state is shown and the action can be cancelled without side effects"),
          ("{persona} yavaş bir bağlantıdayken",
           "işlem {sec3} saniyeden uzun sürdüğünde",
           "ilerleme durumu gösterilir ve işlem yan etki bırakmadan iptal edilebilir")),
 ("happy", ("the {persona} completes the action successfully",
            "the confirmation is shown",
            "it names what happened and what the {persona} can do next"),
           ("{persona} işlemi başarıyla tamamladığında",
            "onay gösterildiğinde",
            "ne olduğunu ve {persona} olarak sırada ne yapabileceğini açıkça söyler")),
 ("edge", ("the input contains leading or trailing whitespace and mixed casing",
           "it is saved",
           "the value is normalised consistently and matching still works"),
          ("girdi başında veya sonunda boşluk ve karışık büyük/küçük harf içerdiğinde",
           "kaydedildiğinde",
           "değer tutarlı biçimde normalleştirilir ve eşleştirme çalışmaya devam eder")),
 ("security", ("the {persona} lost the permission after the page was loaded",
               "they trigger the action from the stale page",
               "the server rejects it and the page refreshes its permission state"),
              ("{persona} sayfa yüklendikten sonra yetkisini kaybettiğinde",
               "eski sayfadan işlemi tetiklediğinde",
               "sunucu işlemi reddeder ve sayfa yetki durumunu tazeler")),
 ("edge", ("the record was deleted by someone else while the page was open",
           "the {persona} submits the form",
           "a clear message says the record no longer exists and offers a way back to the list"),
          ("sayfa açıkken kayıt başkası tarafından silindiğinde",
           "{persona} formu gönderdiğinde",
           "kaydın artık var olmadığını söyleyen net bir mesaj ve listeye dönüş yolu sunulur")),
 ("nfr", ("the feature is used at peak hour",
          "{conc} people use it at the same time",
          "p95 response time stays within the agreed budget for {surface}"),
         ("özellik yoğun saatte kullanıldığında",
          "{conc} kişi aynı anda kullandığında",
          "p95 yanıt süresi {surface} için kararlaştırılan bütçe içinde kalır")),
 ("error", ("the request fails validation on the server but passed on the client",
            "the response comes back",
            "the server message is shown rather than a generic error"),
           ("istek istemcide geçip sunucuda doğrulamaya takıldığında",
            "yanıt döndüğünde",
            "genel bir hata yerine sunucunun verdiği mesaj gösterilir")),
 ("state", ("the {persona} opens {surface} on a second device",
            "they look at the same record",
            "both devices show the same state without a manual refresh"),
           ("{persona} {surface} bölümünü ikinci bir cihazda açtığında",
            "aynı kayda baktığında",
            "iki cihaz da elle yenileme gerekmeden aynı durumu gösterir")),
 ("edge", ("the {persona} pastes content that is longer than the field allows",
           "they try to save",
           "the limit is stated before saving and the text is not silently truncated"),
          ("{persona} alanın izin verdiğinden uzun bir içerik yapıştırdığında",
           "kaydetmeye çalıştığında",
           "limit kaydetmeden önce belirtilir ve metin sessizce kırpılmaz")),
 ("security", ("the action is triggered from an external site",
               "the request arrives without a valid CSRF token",
               "it is rejected and the attempt is logged"),
              ("işlem dış bir siteden tetiklendiğinde",
               "istek geçerli bir CSRF anahtarı olmadan geldiğinde",
               "istek reddedilir ve deneme loglanır")),
 ("happy", ("the {persona} uses {obj} for the first time",
            "they open {surface}",
            "an empty state explains what {obj} does and how to start"),
           ("{persona} {obj} özelliğini ilk kez kullandığında",
            "{surface} bölümünü açtığında",
            "{obj} özelliğinin ne işe yaradığını ve nasıl başlanacağını anlatan bir boş durum gösterilir")),
 ("edge", ("the {persona} performs the action and immediately undoes it",
           "the undo completes",
           "the system returns to the exact state before the action, including counters"),
          ("{persona} işlemi yapıp hemen geri aldığında",
           "geri alma tamamlandığında",
           "sistem sayaçlar dahil işlem öncesindeki duruma birebir döner")),
 ("nfr", ("the change ships",
          "it runs in production for a week",
          "the team can answer from dashboards how often {obj} is used and where it fails"),
         ("değişiklik yayına alındığında",
          "üretimde bir hafta çalıştığında",
          "ekip panolardan {obj} özelliğinin ne sıklıkta kullanıldığını ve nerede başarısız olduğunu görebilir")),
 ("error", ("the {persona} is not authenticated any more",
            "they submit the form",
            "they are sent to sign-in and returned to the same form with their input intact"),
           ("{persona} artık kimlik doğrulamasına sahip değilken",
            "formu gönderdiğinde",
            "girişe yönlendirilir ve girdileri korunmuş halde aynı forma geri getirilir")),
 ("edge", ("the list or result set is filtered to a single item",
           "the {persona} views it",
           "the layout does not break and bulk controls are hidden rather than disabled"),
          ("liste veya sonuç kümesi tek bir kayda indiğinde",
           "{persona} görüntülediğinde",
           "düzen bozulmaz ve toplu işlem kontrolleri devre dışı bırakılmak yerine gizlenir")),
 ("security", ("the exported or displayed data includes another user's identifier",
               "the {persona} views it",
               "identifiers are shown only where the {persona} already has access to that record"),
              ("dışa aktarılan veya gösterilen veri başka bir kullanıcının kimliğini içerdiğinde",
               "{persona} görüntülediğinde",
               "kimlikler yalnızca {persona} o kayda zaten erişebiliyorsa gösterilir")),
]


# butun pattern'lere eklenebilecek ortak AC'ler
COMMON = [
 ("a11y", ("the feature is used with a screen reader",
           "the user navigates {surface} with the keyboard only",
           "every control is reachable, labelled and has a visible focus state"),
          ("özellik ekran okuyucu ile kullanıldığında",
           "kullanıcı {surface} üzerinde yalnızca klavyeyle gezindiğinde",
           "her kontrol erişilebilir, etiketli ve görünür odak durumuna sahiptir")),
 ("nfr", ("the feature is released",
          "it is used in production",
          "usage and error events are emitted with a trace id for debugging"),
         ("özellik yayına alındığında",
          "üretimde kullanıldığında",
          "hata ayıklama için izleme kimlikli kullanım ve hata olayları üretilir")),
 ("a11y", ("the interface is rendered in Turkish",
           "any label or error message is shown",
           "no string is hard-coded and text expansion does not break the layout"),
          ("arayüz Türkçe gösterildiğinde",
           "herhangi bir etiket veya hata mesajı görüntülendiğinde",
           "hiçbir metin koda gömülü değildir ve uzayan metin düzeni bozmaz")),
]


PARAM_POOL = {
    "ms":       [200, 300, 500, 800, 1000],
    "sec2":     [2, 2, 3],
    "sec3":     [3, 4, 5],
    "sec5":     [5, 8, 10],
    "sec15":    [10, 15, 20, 30],
    "sec30":    [15, 30, 45, 60],
    "hrs":      [12, 24, 48, 72],
    "items":    [50, 100, 200, 500],
    "rows":     ["10.000", "25.000", "50.000"],
    "rows_big": ["100.000", "250.000", "1 milyon"],
    "conc":     [50, 100, 250, 500],
    "ntry":     ["three", "four", "five"],
}
PARAM_POOL_TR = dict(PARAM_POOL, ntry=["üç", "dört", "beş"],
                     rows_big=["100.000", "250.000", "1 milyon"])


def build_acs(feature, rng, lang, count=None):
    """Bir feature icin AC listesi uretir. En az 1 happy + 1 error/edge icerir."""
    pool = list(AC.get(feature.pattern, AC["form"]))
    # ortak (a11y/nfr) kriterler her sette degil, ucte bir olasilikla eklenir:
    # aksi halde ayni iki cumle butun veri setini doldurur
    common = list(COMMON)
    rng.shuffle(common)
    if rng.random() < 0.34:
        pool = pool + common[:1]
    cross = [c for c in CROSS if len(c) == 3]
    rng.shuffle(cross)
    pool = pool + cross[:rng.randint(3, 5)]

    happy = [a for a in pool if a[0] == "happy"]
    negative = [a for a in pool if a[0] in ("error", "edge", "security")]
    rest = [a for a in pool if a not in happy and a not in negative]
    rng.shuffle(negative)
    rng.shuffle(rest)

    n = count or rng.choice([3, 3, 4, 4, 5, 5, 6])
    chosen = happy[:1] + negative[:max(2, n - 2)] + rest
    chosen = chosen[:n]

    src = PARAM_POOL if lang == "en" else PARAM_POOL_TR
    subs = dict(
        obj=feature.ent.get("obj_en" if lang == "en" else "obj_tr", "feature"),
        surface=feature.ent.get("surface_en" if lang == "en" else "surface_tr", "the screen"),
        persona=feature.persona_en if lang == "en" else feature.persona_tr,
        component=feature.component,
        **{k: rng.choice(v) for k, v in src.items()},
    )
    out = []
    for i, (cat, en, tr) in enumerate(chosen, 1):
        g, w, t = (en if lang == "en" else tr)
        out.append({
            "id": f"AC{i}",
            "category": cat,
            "given": g.format(**subs),
            "when": w.format(**subs),
            "then": t.format(**subs),
        })
    return out
